// Generates frontend/src/lib/question-data/ from backend/seed_data/*.json
//
// Split into per-category files so Vite code-splits them:
//   question-data/categories/{category}.js  — one per raw category
//   question-data/index.js                  — dynamic import all categories
//
// The index uses import.meta.glob so Vite creates a separate chunk per category,
// enabling parallel HTTP/2 download and per-category cache invalidation.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const seedDir = path.resolve(__dirname, "../../backend/seed_data");
const outDir = path.resolve(__dirname, "../src/lib/question-data");
const catsDir = path.resolve(outDir, "categories");

// ── Read & assign IDs ─────────────────────────────────────────
const files = fs.readdirSync(seedDir).filter(f => f.endsWith(".json")).sort();
const byCategory = Object.create(null);
let id = 1;

for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(seedDir, f), "utf-8"));
  for (const q of data) {
    const cat = q.category;
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push({ ...q, id: id++ });
  }
}

const sortedCats = Object.keys(byCategory).sort();

// ── Write per-category files ───────────────────────────────────
fs.mkdirSync(catsDir, { recursive: true });

for (const cat of sortedCats) {
  const questions = byCategory[cat];
  const safeName = cat.replace(/[/\\?%*:|"<>]/g, "_") || "unknown";
  const content = `// Auto-generated by scripts/generate-data.js. Do not edit.\n// Category: ${cat} — ${questions.length} questions\nexport const category = ${JSON.stringify(cat)};\nexport const questions = ${JSON.stringify(questions)};\n`;
  fs.writeFileSync(path.join(catsDir, `${safeName}.js`), content, "utf-8");
}

// ── Write index.js with Vite code-splitting ────────────────────
const globPattern = "./categories/*.js";
const indexContent = `// Auto-generated by scripts/generate-data.js. Do not edit.
// ${sortedCats.length} categories, ${id - 1} total questions

const categoryModules = import.meta.glob(${JSON.stringify(globPattern)}, { eager: false });

export const questions = [];
export const categoryIndex = {};

const _loader = (async () => {
  const entries = await Promise.all(
    Object.entries(categoryModules).map(async ([catPath, loader]) => {
      const mod = await loader();
      return { path: catPath, mod };
    })
  );

  entries.sort((a, b) => a.path.localeCompare(b.path));

  for (const { mod } of entries) {
    categoryIndex[mod.category] = mod.questions;
    questions.push(...mod.questions);
  }
})();

await _loader;
`;

fs.writeFileSync(path.join(outDir, "index.js"), indexContent, "utf-8");

// ── Remove legacy single-file ──────────────────────────────────
const legacyFile = path.resolve(__dirname, "../src/lib/question-data.js");
if (fs.existsSync(legacyFile)) {
  fs.unlinkSync(legacyFile);
  console.log(`Removed legacy ${legacyFile}`);
}

console.log(`Generated ${catsDir}/ — ${sortedCats.length} category files (${id - 1} questions)`);
