// Generates frontend/src/lib/question-data.js from backend/seed_data/*.json
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const seedDir = path.resolve(__dirname, "../../backend/seed_data");
const outFile = path.resolve(__dirname, "../src/lib/question-data.js");

const files = fs.readdirSync(seedDir).filter(f => f.endsWith(".json")).sort();
let allQuestions = [];
let id = 1;

for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(seedDir, f), "utf-8"));
  for (const q of data) {
    allQuestions.push({
      id: id++,
      category: q.category,
      difficulty: q.difficulty,
      type: q.type,
      title: q.title,
      content: q.content,
      answer: q.answer,
      hints: q.hints || [],
      tags: q.tags || [],
      options: q.options || [],
      company: q.company || "",
    });
  }
}

const js = `// Auto-generated by scripts/generate-data.js. Do not edit.
// Total: ${allQuestions.length} questions
export const questions = ${JSON.stringify(allQuestions, null, 2)};
`;

fs.writeFileSync(outFile, js, "utf-8");
console.log(`Generated ${outFile} — ${allQuestions.length} questions`);
