// Generates frontend/src/lib/question-data/ from backend/seed_data/*.json
//
// Outputs:
//   question-data/categories/{category}.js  — full data per category (lazy-loaded)
//   question-data/index.js                  — lightweight question index + lazy loaders
//
// The index contains a slim metadata-only question list loaded eagerly,
// while full question content (content, answer, options) is loaded on demand
// via loadCategory() / loadAll(). This reduces initial bundle size by ~83%.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const seedDir = path.resolve(__dirname, "../../backend/seed_data");
const outDir = path.resolve(__dirname, "../src/lib/question-data");
const catsDir = path.resolve(outDir, "categories");

// ── Read & assign IDs ─────────────────────────────────────────
const files = fs.readdirSync(seedDir).filter(f => f.endsWith(".json")).sort();
const byCategory = Object.create(null);
let id = 1;

for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(seedDir, f), "utf-8"));
  for (const q of data) {
    const cat = q.category;
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push({ ...q, id: id++ });
  }
}

const sortedCats = Object.keys(byCategory).sort();

// ── Write per-category files (full data, lazy chunks) ─────────
fs.mkdirSync(catsDir, { recursive: true });
// Clean stale files from previous runs
for (const f of fs.readdirSync(catsDir)) {
  fs.rmSync(path.join(catsDir, f), { force: true });
}

for (const cat of sortedCats) {
  const questions = byCategory[cat];
  const safeName = cat.replace(/[/\\?%*:|"<>]/g, "_") || "unknown";
  const content = `// Auto-generated by scripts/generate-data.js. Do not edit.\n// Category: ${cat} — ${questions.length} questions\nexport const category = ${JSON.stringify(cat)};\nexport const questions = ${JSON.stringify(questions)};\n`;
  fs.writeFileSync(path.join(catsDir, `${safeName}.js`), content, "utf-8");
}

// ── Write index.js ────────────────────────────────────────────
// Part 1: Lightweight question index (metadata only, loaded eagerly)
// Part 2: Lazy category loaders using import.meta.glob
const globPattern = "./categories/*.js";

// Build questionIndex with only the fields needed for list/search/stats
const questionIndex = [];
for (const cat of sortedCats) {
  for (const q of byCategory[cat]) {
    questionIndex.push({
      id: q.id,
      category: q.category,
      difficulty: q.difficulty,
      type: q.type,
      title: q.title,
      tags: q.tags || [],
      company: q.company || "",
    });
  }
}

const indexContent = `// Auto-generated by scripts/generate-data.js. Do not edit.
// ${sortedCats.length} categories, ${id - 1} total questions

// ── Lightweight question index (eagerly loaded) ───────────────
// Metadata only — ~16% of full data size. Use for listing, stats, search.
export const questionIndex = ${JSON.stringify(questionIndex)};


// ── Lazy full-data loaders ────────────────────────────────────
const _categoryModules = import.meta.glob(${JSON.stringify(globPattern)}, { eager: false });

const _loaderMap = {};
for (const [path, loader] of Object.entries(_categoryModules)) {
  const name = path.replace("./categories/", "").replace(".js", "");
  _loaderMap[name] = loader;
}

export const questions = [];
export const categoryIndex = {};
const _loadingCategories = {};

export async function loadCategory(name) {
  if (_loadingCategories[name]) return _loadingCategories[name];
  const loader = _loaderMap[name];
  if (!loader) throw new Error(\`Category not found: \${name}\`);
  _loadingCategories[name] = loader().then(mod => {
    categoryIndex[name] = mod.questions;
    questions.push(...mod.questions);
  }).catch(err => {
    delete _loadingCategories[name];
    throw err;
  });
  return _loadingCategories[name];
}

export async function loadAll() {
  const names = Object.keys(_loaderMap).sort();
  await Promise.all(names.map(loadCategory));
}
`;

fs.writeFileSync(path.join(outDir, "index.js"), indexContent, "utf-8");

// ── Remove legacy single-file ─────────────────────────────────
const legacyFile = path.resolve(__dirname, "../src/lib/question-data.js");
if (fs.existsSync(legacyFile)) {
  fs.unlinkSync(legacyFile);
  console.log(`Removed legacy ${legacyFile}`);
}

console.log(`Generated ${catsDir}/ — ${sortedCats.length} category files (${id - 1} questions)`);
console.log(`Generated index.js — questionIndex: ${questionIndex.length} entries`);
