# -*- coding: utf-8 -*-
"""Generate additional ai_infra questions (append to existing ai_infra.json)."""
import json, sys

questions = []

def q(cat, diff, typ, title, content, answer, hints, tags):
    questions.append({
        "category": cat, "difficulty": diff, "type": typ,
        "title": title, "content": content, "answer": answer,
        "hints": hints, "tags": tags
    })

# ==================== GPU Partitioning & Scheduling ====================

q("ai_infra", "medium", "short_answer",
  'NVIDIA GPU 分区技术：MIG vs MPS vs Time-Slicing',
  'NVIDIA GPU 的三种分区技术——MIG（Multi-Instance GPU）、MPS（Multi-Process Service）、Time-Slicing——各自的工作原理是什么？分别在什么场景下使用？如何选择？',
  '三种分区技术解决的核心问题：让多个 AI 工作负载共享一张 GPU，提高 GPU 利用率。\n\n1. MIG（Multi-Instance GPU，A100/H100/B200）\n   原理：在硬件层面将 GPU 分割为多个独立实例。每个实例有独立的显存、缓存、SM 子集和内存控制器。硬件隔离——实例间完全独立（一个实例的故障不影响其他实例）。\n   分区粒度：A100 支持最多 7 个实例（1g.5gb、2g.10gb、3g.20gb、4g.20gb、7g.40gb/80gb）。H100 支持最多 7 个实例（增强的 MIG 配置）。B200 支持更多灵活配置。\n   适用场景：多租户 GPU 共享（不同用户的推理任务严格隔离）、混合负载（一个实例跑推理、一个实例跑训练）。\n   局限：需要 GPU 硬件支持（仅 A100/H100/B200 系列），NVLINK 在 MIG 模式下不可用。\n\n2. MPS（Multi-Process Service）\n   原理：软件层级的 CUDA 流合并。多个 CUDA 进程的 Kernel 提交到同一个 CUDA Stream 上执行，减少调度开销。\n   工作方式：MPS Server 进程统一接收 CUDA 调用 → 合并 Kernel 提交 → 批量调度到 GPU。可将小 batch 合并为大 batch 提高利用率。\n   优点：兼容所有 NVIDIA GPU（不需要 A100 等新硬件）；对应用透明（不需要改代码）。\n   局限：进程间无硬件隔离——一个进程的 CUDA 错误可能导致 MPS Server 崩溃；显存不隔离——可以抢占其他进程的显存。\n   适用场景：多个小推理任务共享 GPU（批量推理场景）、原型验证阶段。\n\n3. Time-Slicing（Kubernetes 原生）\n   原理：将 GPU 时间片按时间轮转分配给不同 Pod。每个 Pod 使用整个 GPU 一段时间片（如 100ms），然后切换到下一个 Pod。\n   实现：K8s Device Plugin + Time-Slicing GPU 调度（NVIDIA 官方支持）。\n   优点：简单——不需要改应用；兼容所有 GPU。\n   局限：无显存隔离——每个 Pod 看到的整块 GPU 显存，但物理上共享。Pod 如果超用显存会导致 OOM kill 其他 Pod；上下文切换开销——GPU 上下文在 Pod 间切换时有开销。\n   适用场景：开发/测试环境的 GPU 共享、对延迟不敏感的批处理任务。\n\n选型建议：\n- 生产环境多租户隔离（安全要求高）→ MIG（硬件隔离）\n- 训练和混合负载 → MIG（稳定、隔离）\n- 批量推理（相同租户）→ MPS（更高的吞吐、无隔离也 OK）\n- 开发测试、CI Runner → Time-Slicing（最简单，对隔离无要求）\n- 注意：真正的生产 GPU 共享通常需要组合使用（如 MIG 做隔离 + MPS 做性能优化）',
  ["MIG 是硬件隔离（最安全），MPS 是 CUDA 流合并（吞吐最高），Time-Slicing 是时间共享（最简单）", "MIG 需要特定 GPU 硬件（A100/H100/B200），其他两种兼容所有 GPU"],
  ["GPU", "MIG", "MPS", "分区", "NVIDIA"])

q("ai_infra", "medium", "short_answer",
  'FlashAttention：加速注意力计算的原理与演进',
  'FlashAttention 系列（v1/v2/v3）的核心优化思想是什么？FlashAttention 如何通过 tiling 和 recomputation 降低显存消耗和计算量？FlashAttention-2 和 FlashAttention-3 的改进点？',
  'FlashAttention 系列解决了 Transformer 推理/训练中的 Attention 计算瓶颈——标准 Attention 需要将完整 N×N 注意力矩阵写入 HBM（高带宽显存），然后读回 SM（流多处理器）计算 softmax，O(N²) 的显存消耗成为长序列的瓶颈。\n\nFlashAttention-1（2022）：核心思想——计算融合 + Tiling（分块计算）。\n将 QKV 矩阵分块（Tiling），每个 Block 在 SRAM（共享内存，~192KB）中完成计算：加载 Q 的一个 Block + K 的对应 Block → 在 SRAM 中计算 S = Q×K^T → 在 SRAM 中计算 Online Softmax（增量式，不需要完整 Attention 矩阵） → 累加结果。Online Softmax——传统 softmax 需要先算完整向量再规约求和；FlashAttention 使用 Safe Softmax 的增量版本，在扫描过程中动态更新归一化因子。\n效果：不需要将 N×N 注意力矩阵写入 HBM（显存从 O(N²) 降到 O(N)）。训练 GPT-2 时速度提升 2-4x，显存占用降低 10x+。\n\nFlashAttention-2（2023）：改进点——1）减少非计算操作——减少 RCC（Reduce、Rescale、Cast）操作的次数，更多时间花在实际矩阵乘上。2）优化 Thread Block 调度——每个 Block 处理更多的矩阵乘（减少 warp 空转）。3）支持 Multi-Query Attention（MQA）和 Grouped-Query Attention（GQA）——针对这些新型 Attention 架构优化。\n效果：比 FlashAttention-1 再提速 2x，达到理论计算效率的 ~70%（H100）和 ~90%（A100）。\n\nFlashAttention-3（2024，Hopper H100 优化）：针对 H100 的特定优化——1）利用 FP8 低精度计算——Hopper 的 Tensor Core 支持 FP8 矩阵乘（比 FP16 快 2x）。Attention 计算中，QK^T 用 FP8 计算，Softmax 用 FP16/FP32 保持精度。2）Async WGMMA（Warp Group Matrix Multiply-Accumulate）——H100 的异步矩阵乘指令，计算与数据加载可以重叠。3）Hopper 的 Shared Memory 增强——H100 的 SRAM 容量提升（256KB vs A100 的 192KB），支持更大 Block Size。4）Warp Specialization——一部分 warp 专门负责数据加载（DMA），另一部分负责计算，实现计算-加载流水线重叠。\n效果：H100 上 Forward + Backward 吞吐比 FlashAttention-2 再提升约 1.5-2x，接近硬件理论峰值。',
  ["FlashAttention 的核心创新是 Tiling + Online Softmax——让 Attention 计算完全在 SRAM 中完成，避免 O(N²) 显存消耗", "FlashAttention-2 优化了 warp 调度，FlashAttention-3 利用了 H100 的 FP8 和异步计算能力"],
  ["FlashAttention", "Attention", "GPU", "显存优化", "推理加速"])

# ==================== Speculative Decoding ====================

q("ai_infra", "hard", "short_answer",
  '推测解码（Speculative Decoding）原理与实现',
  '推测解码（Speculative Decoding）如何加速 LLM 推理？Draft Model 和 Verifier 的两阶段机制是什么？如何选择 Draft Model？Speculative Decoding 的加速比受哪些因素影响？',
  '推测解码（Speculative Decoding）是一种不改变输出质量而加速 LLM 推理的技术。核心思想：用一个快速的草稿模型（Draft Model）生成一批候选 Token，然后用目标模型（Verifier/LM）一次性验证，而不是逐个 Token 生成。\n\n两阶段机制：\nPhase 1 — Draft：用轻量级 Draft Model（如 125M 参数）自回归生成 γ（如 5-10）个候选 Token。速度很快（小模型）。\nPhase 2 — Verification：用目标 LLM（如 70B 参数）对 γ 个候选 Token 做一次并行 Forward Pass。目标模型计算候选序列中每个位置的概率分布。Rejection Sampling：从 Draft → Output 路径上接受概率高的 Token，拒绝概率低的 Token 并纠正（从目标模型采样）。保证：输出分布与直接目标模型采样完全一致（数学等价）。\n\nDraft Model 的选择：\n1. 同一架构的小模型——LLaMA-68M 作为 LLaMA-7B 的 Draft。共享词表（Embedding 层兼容），容易搭配。\n2. 同一模型的浅层截断——取目标模型的前几层作为 Draft（不需要额外模型文件）。不需要额外加载模型。\n3. 独立的轻量模型——Medusa（增加多个推测 Head，每个 Head 预测一个偏移位置的 Token，不需要单独的 Draft Model）。\n4. Self-Speculative Decoding——目标模型自己跳过中间层来做快速 Draft（Skip Decoding），减少参数化的 Draft Model 部署。\n\n加速比影响因素：\n1. Acceptance Rate（接受率）——Draft Model 和目标模型概率分布的匹配程度。匹配度高（如同一系列的模型）时接受率达 0.8-0.95，加速比 2-3x。匹配度低时加速效果差（甚至可能变慢）。\n2. γ（推测长度）——每个推测窗口生成的候选 Token 数。γ 太小时加速收益有限；γ 太大时验证阶段的计算量增加 + Draft 阶段来不及补充候选。最优 γ 通常在 5-10 之间（经验值）。\n3. 计算瓶颈——当推理受内存带宽限制（Memory-Bound）时 Speculative Decoding 最有效（greedy decoding，batch size=1）。当推理已经受计算限制（Compute-Bound，大 batch size）时，增益有限。\n4. Hardware——在 H100 等硬件上，FP8 推理 + 优化的 Draft Model 可以实现更好的加速比。\n\n部署注意事项：\n- 额外服务开销：Draft Model 需要单独部署或和 Target Model 共享 GPU（Draft 阶段使用小部分 GPU 资源）。\n- 延迟权衡：Draft Model 推理 + 目标模型验证的总耗时会略高于单次 Token 生成，但一次验证产出多个 Token。\n- 实际生产效果：LLaMA-7B + 125M Draft 在 A100 实测约 1.8-2.5x 加速。推理服务（vLLM、TGI）已原生支持 Speculative Decoding。',
  ["Speculative Decoding 不改变输出分布——数学严格等价于直接从目标模型采样", "加速比取决于 Draft 匹配度（Acceptance Rate）和 γ 选择"],
  ["LLM", "推测解码", "推理加速", "Speculative Decoding", "优化"])

q("ai_infra", "hard", "short_answer",
  'VLLM 的 Automatic Prefix Caching 与 SGMK 稀疏 Attention',
  'vLLM 的 Automatic Prefix Caching（APC）如何工作？SGLang 的 RadixAttention 和 vLLM 的 APC 在 Prefix Cache 管理上有什么不同？Sparse Attention 和 StreamingLLM 如何处理超长上下文？',
  'KV Cache 复用是 LLM 推理中减少 Prefill 阶段计算的关键优化。当请求的前缀（System Prompt + 历史对话）重复出现时，可以直接复用之前缓存的 KV Cache，避免重复计算。\n\nvLLM Automatic Prefix Caching（APC）：\n原理：vLLM 的 KV Cache Block 覆盖全局——不同请求之间的 Block 如果 Token 序列相同（Hash 一致），则自动共享。\n实现细节：每个 KV Cache Block 计算内容的 hash（基于 Block 内 Token ID 的 Hash）。Hash Table 存储所有已生成 Block 的指针。新请求的 Prefill 阶段，逐 Block 匹配 hash——如果命中缓存，跳过该 Block 的 Prefill 计算。APC 是自动的——开发者不需要显式指定 prefix。\n适用场景：共享 System Prompt 的对话服务、多轮对话（前几轮共享 prefix）、批量 Prompt 处理。\n\nSGLang RadixAttention（基于 Radix Tree）：\n原理：使用 Radix Tree（前缀树/字典树）管理 KV Cache。每个节点对应一个 Token 序列前缀，节点存储该前缀的 KV Cache。\n特点：1）共享粒度更细——Radix Tree 可以匹配任意重合的前缀（不仅仅是 Block 级别的 exact match）。2）支持 Cache Eviction 的 LRU——当 GPU 显存不足时，Radix Tree 以 LRU 策略淘汰最久未命中的前缀分支。3）写入策略——新生成的 KV Cache 写入 Radix Tree 的共享/扩展路径，而不是每次创建新 Block。\nvs vLLM APC：RadixAttention 支持更细粒度的 Prefix 匹配（Token 级 vs Block 级），在 prompt 多样化的场景下命中率更高。vLLM APC 使用 Hash 匹配实现简单且高效（Block 级粒度在大 Batch 场景下开销更低）。\n\nStreamingLLM（Handle Long Context 的高效方案）：\n问题：LLM 处理超长上下文时，所有 KV Cache 占满 GPU 显存，但实际有用的注意力集中在开头 Token（Attention Sink）和最近的 Token。\n方案：1）保留 Attention Sink（前 4 个 Token）——这些 Token 虽然在语义上不重要，但被模型用来归一化注意力分布。去掉会导致模型崩溃。2）保留最近的 Token（滑动窗口）——最近 N 个 Token 的上下文用于生成。3）丢弃中间的 Token——中间的 Token 注意力值很低，去掉对输出质量影响最小。\n效果：理论上可以处理无限长度的文本（但模型在长程依赖上仍有退化）。适用于长对话、长文档处理。\n\nSparse Attention（BigBird / Longformer / Sparse Transformer）——在训练阶段就设计稀疏注意力模式（全局 Token + 滑动窗口 + 随机 Token），将 Attention 复杂度从 O(N²) 降到 O(N log N)。FlashAttention 和 Sparse Attention 互补：FlashAttention 优化稠密注意力的计算效率，Sparse Attention 减少需要计算的 Token 数量。',
  ["KV Cache 共享通过前缀匹配（vLLM APC 的 Hash Match vs SGLang Radix Tree 的 Token 级前缀匹配）", "StreamingLLM 通过 Attention Sink + 滑动窗口实现常驻上下文"],
  ["vLLM", "SGLang", "Prefix Cache", "KV Cache", "长上下文"])

# ==================== Model Serving & Deployment ====================

q("ai_infra", "medium", "short_answer",
  'LLM 推理的容器化与部署优化',
  '如何为 LLM 推理服务设计高效的 Docker 容器和部署策略？模型热加载、GPU 内存预热、Horizontial Scaling 的最佳实践是什么？',
  'LLM 推理服务的部署优化涉及容器镜像、GPU 管理、弹性伸缩三个层面。\n\n1. 容器镜像优化\n   - 基础镜像选择：使用 NVIDIA CUDA Base（如 nvidia/cuda:12.4.0-runtime-ubuntu22.04）而不是 Devel 版（减小 2GB+）。或者使用 PyTorch 官方镜像（pytorch/pytorch:2.4.0-cuda12.4-runtime）。\n   - 多阶段构建：Build 阶段使用 Devel 镜像（需要编译器），Runtime 阶段切到 Runtime 镜像。只拷贝编译产物 + Python 依赖。\n   - 模型文件分离：不使用 Docker Image 打包模型权重（镜像太大，推送和启动慢）。使用 Volume 挂载或对象存储（S3/GCS/NFS）动态加载。\n   - 优化技巧：安装 CUDA 内核共享库（nvjitlink）以支持 JIT 编译。设置环境变量 CUDA_CACHE_MAXSIZE 控制缓存大小。使用 torch.compile 或 vLLM 内置优化。\n\n2. GPU 内存预热（Warm-up）\n   - 冷启动问题：LLM 服务首次加载模型耗时 20 秒 - 5 分钟（取决于模型大小和存储速度）。加载后首次推理会产生 CUDA Kernel 编译开销（约 10-30 秒的预热期）。\n   - 预热策略：在容器启动脚本中发送 Warmup Request（一个标准长度的 Prompt）——触发 CUDA Kernel 编译和缓存。也可以在部署前运行一个 Test Batch。\n   - 持久化 CUDA Graph：CUDA Graph 可以捕获并保存 GPU Kernel 执行图，避免每次重放 Kernel Launch 的开销。vLLM 支持 CUDA Graph 缓存到磁盘，下次启动直接加载。\n\n3. Horizontal Scaling（水平扩展）\n   - GPU 节点分组：相同模型的服务部署在相同 GPU 类型的节点池中（避免异构 GPU 导致调度问题）。\n   - 自动扩缩容指标：不依赖 CPU/Memory（LLM 服务的瓶颈在 GPU），使用 Custom Metrics——In-flight Requests、GPU Memory Utilization、Queue Depth。\n   - HPA（Horizontal Pod Autoscaler）：基于 Custom Metric 的 Pod 自动扩展。策略：在 Queue Depth > 5 时扩容，Queue Depth < 2 时缩容。\n   - 优雅缩容：LLM 推理中的请求可能有几十秒——需要配置 PreStop Hook 等待正在处理的请求完成再终止 Pod。\n\n4. 部署拓扑\n   - 单模型单副本：最简单的部署（1 Pod = 1 LLM 服务）。适合小规模。\n   - 单模型多副本：前面加负载均衡（如 Nginx/Envoy/GLB）。注意 LLM 推理的无状态设计（所有请求独立，不需要共享 KV Cache 时）。\n   - 多模型共享 GPU：通过 MIG 或 MPS 分区在同一个 GPU 上部署多个小模型。\n\n5. 生产运维要点\n   - 健康检查：Readiness Probe 检测模型已加载完成、Liveness Probe 检测服务进程存活、Startup Probe 给模型加载留出充分时间。\n   - 资源限额：设置 GPU Memory 上限（避免 OOM）、设置 CPU/Memory request 和 limit（影响 K8s 调度决策）。\n   - 日志和监控：输出 Prometheus 格式的推理指标（请求数、Token 吞吐、P50/P95 延迟、GPU 利用率），用 Grafana 展示。',
  ["模型权重不打包进 Docker 镜像（独立用 Volume/对象存储管理）——镜像大小从 30GB 降到 1-2GB", "预热（Warm-up Request）+ CUDA Graph 缓存可以解决冷启动问题"],
  ["Docker", "部署", "GPU", "K8s", "推理"])

# ==================== Cost & Operations ====================

q("ai_infra", "hard", "short_answer",
  'AI 基础设施成本管理与优化',
  'AI 基础设施的成本构成有哪些？如何在 GPU 实例选择、推理服务配置、训练作业调度中系统性地优化成本？常见的成本陷阱有哪些？',
  'AI 基础设施成本主要由三部分构成：GPU 算力成本（60-80%）、存储成本（5-15%）、网络和数据传输成本（5-10%）。以下从各层面梳理优化策略：\n\n1. GPU 实例选型优化\n   - 按需 vs 预留 vs Spot：按需实例最贵（适合弹性、不能中断的工作负载）。预留实例/承诺使用折扣（1 年或 3 年）可节省 40-60%（适合训练、长期推理）。Spot/抢占式实例可节省 60-90%（适合 Checkpoint 的分布式训练、批处理、ML 实验）。\n   - GPU 型号选择：推理服务常选择 T4（性价比高，INT8 推理快）或 L4（比 T4 快 2x，视频/AI 推理优化）。训练选择 A100（训练 LLM 性价比最优）或 H100（训练速度最快，价格也最高）。\n   - 省钱组合：训练用预留实例（稳定运行），实验调参用 Spot 实例（可以中断），推理用按需（弹性伸缩）或预留（长期稳定流量）。\n\n2. 推理服务成本优化\n   - 批处理（Batching）——增加 Batch Size 提高 GPU 利用率，降低每 Token 成本。Continuous Batching（vLLM/TGI）自动收集请求成批，2-4x 吞吐提升。\n   - 模型量化——FP16 → INT4 推理：显存需求降低 4x，推理吞吐提升 2-3x，精度损失可控（< 2% perplexity）。代价是一次性的量化校准成本。\n   - 模型路由——简单查询路由到便宜模型（Claude Haiku/Llama-3-8B），复杂查询用昂贵模型（Claude Opus/GPT-4）。简单分类器（基于 Query 长度、关键词）实现路由，可节省 30-50% 推理成本。\n   - Cache 层——见前面的缓存策略。Response Cache + Semantic Cache 可以减少 20-40% 的重复 LLM 调用。\n   - 自动扩缩容——根据流量自动扩展/缩减副本数。流量低谷期（夜间）缩容到最小规模（通常是 1-2 个副本）。\n\n3. 训练成本优化\n   - Spot 实例训练：使用 Checkpointing 定期保存，Spot 回收时从最近 Checkpoint 恢复。配合 AWS Fault-Tolerant Training / GKE Preemption Handling。\n   - 混合精度训练：BF16/FP16 训练比 FP32 快 2-3x，显存少 50%。\n   - Gradient Checkpointing：以计算换显存，将中间激活值重新计算而不是存储。可以训练更大的 Batch Size 或模型。\n   - 弹性训练：Kubernetes + Volcano/MPI Operator 调度训练 Job。支持动态增删 GPU Worker（Spot 实例回收时自动降级到更少 Worker）。\n\n4. 存储和网络优化\n   - 训练数据：对象存储（S3/GCS）存储数据集，训练时 Streaming 加载（不需要先下载到本地）。\n   - 模型 Checkpoint：只保留最近 N 个 Checkpoint，旧删。增量 Checkpoint（只保存变化部分）比全量 Checkpoint 小 10-100x。\n   - 内网传输：将数据 Bucket 和 GPU 实例部署在同一 Region 中（避免跨 Region 数据传输费）。\n\n5. 常见成本陷阱\n   - 未使用的预留实例：买了 1 年预留但实际只用了一半。按月评估实际利用率再做承诺。\n   - 闲置 GPU：开发环境和测试环境的 GPU 24/7 运行但只在工作时间使用。用 K8s + Node Auto-scaling 在非工作时间缩容到 0。\n   - 过大的 Batch Size：Batch Size 太大导致 GPU OOM（作业失败重跑浪费资源）。从安全 Batch Size 开始逐步调优。\n   - 不必要的长 Context：Prompt 太长（包含大量 Token）导致 Prefill 计算成本高。精简 Prompt（只传必要上下文）可以节省 30-50% 的输入 Token 费用。\n   - 单次推理的 Overhead：LLM API 的 Token 计费中，输出 Token 通常比输入 Token 贵 2-3x（GPT-4: $10/1M 输入 vs $30/1M 输出）。精简输出（要求模型直接给答案而不是冗长回复）。',
  ["成本最大的杠杆是 GPU 选型 + 推理 Batching（Continuous Batching 可提升 2-4x 吞吐）", "开发/测试环境的 GPU 闲置是最常见的隐性成本——用自动缩容降到 0"],
  ["成本", "GPU", "优化", "运维", "FinOps"])

q("ai_infra", "easy", "short_answer",
  'ML 实验跟踪与模型注册',
  '机器学习实验跟踪（Experiment Tracking）和模型注册（Model Registry）有什么区别？MLflow、Weights & Biases、Neptune 等工具的选型考虑是什么？',
  'ML 实验跟踪和模型注册是 MLOps 的两个不同概念，经常混淆：\n\n1. 实验跟踪（Experiment Tracking）——记录每次训练实验的元数据\n   记录内容：超参数（learning rate、batch size、epochs）、指标（loss、accuracy、BLEU、perplexity）、代码版本（Git commit hash）、环境（Python 版本、CUDA 版本、PyTorch 版本）、Artifacts（模型权重、TensorBoard 日志、Confusion Matrix）。\n   用途：对比不同实验的效果、找到最优超参数组合、回溯能复现某个结果的实验。\n\n2. 模型注册（Model Registry）——管理模型版本的生命周期\n   管理内容：模型版本管理（v1、v2、……）、模型状态（Staging / Production / Archived）、模型元数据（哪个实验产出的、谁批准的、评估指标）、部署历史（模型 X 版本在什么时候部署到哪个环境）。\n   用途：模型版本管理和发布审批、模型回滚、模型部署的审计链。\n\n工具对比：\n\n1. MLflow（开源，Databricks）\n   - 实验跟踪：MLflow Tracking——自动记录参数/指标/Artifacts，支持本地文件或 SQLite/PostgreSQL 后端。\n   - 模型注册：MLflow Model Registry——管理模型版本、Stage 转换（Staging → Production）、Docker 部署。\n   - 优势：开源免费、全流程（跟踪+注册+部署）、与 HuggingFace 集成好。\n   - 劣势：UI 较为基础、大规模实验时查询速度下降。\n   - 适合：需要全流程管理的团队、预算有限的场景。\n\n2. Weights & Biases（W&B，商业 SaaS/自托管）\n   - 实验跟踪：WandB 核心功能——自动记录超参数和指标、交互式可视化（并行坐标图、学习曲线对比）、自动报告生成。\n   - 模型注册：W&B Artifacts——模型版本管理和 Lineage 追踪（每个模型版本追溯训练数据和代码）。\n   - 优势：最好的可视化体验（拖拽对比实验）、团队协作好（共享 Report）、HuggingFace 深度集成。\n   - 劣势：SaaS 模式下数据离站、大团队成本较高。\n   - 适合：研究团队（需要丰富的可视化对比）、快速迭代的场景。\n\n3. Neptune.ai（商业 SaaS）\n   - 优势：支持非 PyTorch 框架（XGBoost、LightGBM 等）、数据隐私控制好（可自托管）、硬件的自动监控（GPU 利用率、内存）。\n   - 适合：多框架混合的团队、需要硬件监控的场景。\n\n4. DVC（Data Version Control，开源）\n   - 实验跟踪：基于 Git 的实验管理（每个实验是 Git 分支 + DVC 数据链接）、与 Git 工作流完全兼容。\n   - 模型注册：DVC Studio 提供模型注册功能（Web UI）。\n   - 优势：不锁平台（数据存在自己的存储上）、Git 原生体验（适合 DevOps 成熟的团队）。\n   - 劣势：可视化较弱、学习曲线陡峭（需要理解 DVC 概念）。\n   - 适合：DevOps 成熟、对数据隐私敏感的团队。\n\n选型建议：\n- 快速起步、小团队 → MLflow（免费，够用）\n- 研究驱动、需要丰富的可视化 → W&B（体验最好）\n- 多框架、需要硬件监控 → Neptune\n- Git 原生工作流、数据隐私优先 → DVC\n- 大企业 → MLflow（自托管）+ 补充工具（如 W&B 做可视化）组合使用',
  ["实验跟踪记录训练过程（超参数/指标/Artifacts），模型注册管理模型版本和部署状态", "MLflow 是最普适的开源选择，W&B 是最好的体验但需要付费"],
  ["MLOps", "实验跟踪", "模型注册", "MLflow", "W&B"])

q("ai_infra", "medium", "short_answer",
  'ML Pipeline 编排与工作流管理',
  '如何设计可生产的 ML Pipeline？Airflow、Kubeflow、Flyte、ZenML 等 Pipeline 编排工具的核心差异是什么？Feature Engineering → Training → Evaluation → Deployment 的自动化流程如何设计？',
  'ML Pipeline 编排的目标是自动化和可复现地从原始数据到生产部署的完整流程。\n\nPipeline 的典型阶段：\n1. Data Ingestion——连接数据源（DB、S3、Kafka）提取原始数据 → 校验 Schema 和数据质量（Great Expectations / Deequ）→ 存储到 Feature Store。\n2. Feature Engineering——从原始数据计算特征 → 数据清洗、转换（缺失值处理、归一化、编码）→ 特征验证（分布对比、漂移检查）→ 写入 Feature Store。\n3. Training——从 Feature Store 拉取训练数据 → 初始化模型配置（超参数来自实验跟踪）→ 分布式训练 → 模型评估（Holdout 数据集）→ 注册到 Model Registry。\n4. Evaluation——在独立的评估数据集上运行 → 对比当前模型和 Production 模型的指标 → 如果指标退化触发告警或阻止部署。\n5. Deployment—将模型打包（Docker + Triton/vLLM 等推理引擎）→ Canary/Blue-Green 部署 → 监控线上指标。\n\n编排工具对比：\n\n1. Apache Airflow——通用工作流编排（非 ML 专用）\n   - 方式：DAG（有向无环图）定义任务依赖关系。每个任务是 Python Operator（训练代码）、Bash Operator（数据预处理命令）或 Kubernetes Pod Operator（K8s Pod 执行）。\n   - 优点：生态最大（1000+ 插件）、调度器成熟（Cron 触发、Backfill、重试）。\n   - 缺点：不是 ML 原生（没有内置的 Experiment Tracking、Model Registry 集成）；每个 Step 的资源管理需要手动处理。\n   - 适合：已有 Airflow 基础设施的团队、Pipeline 以数据处理为主的场景。\n\n2. Kubeflow（K8s 原生 ML 平台）\n   - 方式：Kubeflow Pipelines——Web UI 可视化构建 ML Pipeline（Python SDK 定义 Component）。每个 Component 运行在独立的 K8s Pod 上（自动资源隔离）。\n   - 组件：Kale（Jupyter Notebook → Pipeline）、KFServing（模型推理服务）、Katib（超参数调优）。\n   - 优点：ML 原生——支持 Notebook、超参数调优、模型推理；K8s 生态（Istio、Knative 集成）。\n   - 缺点：运维复杂（需要维护 K8s + Kubeflow 集群）；资源消耗大（需要专门的 Cluster）。\n   - 适合：已有 K8s 基础设施的中大型团队。\n\n3. Flyte（Lyft 开源，ML 原生工作流）\n   - 方式：Python 装饰器标记 Task（@task）和 Workflow（@workflow）。自动序列化输入/输出（类型安全）。每个 Task 在独立容器中执行。\n   - 优点：ML 原生——支持 GPU Task、自动重试和资源管理、Task 级别缓存（相同输入跳过执行）。类型安全——输入/输出 Schema 校验。\n   - 缺点：社区小于 Airflow、Python 生态绑定（非 Python 工具支持弱）。\n   - 适合：需要类型安全和缓存的中大规模 ML 团队。\n\n4. ZenML——ML 原生 Pipeline 框架（较新）\n   - 方式：Python DSL（@step → @pipeline）。Stack concept（各组件可插拔：A 用 MLflow Tracking + S3 Artifact Store，B 用 W&B + GCS）。\n   - 优点：Stack 抽象——轻松切换不同 Backend（开发用本地，生产用 K8s）。内置 ML 集成——MLflow、W&B、Great Expectations 的 1st-class 集成。\n   - 缺点：项目较新（稳定性不如 Airflow/Kubeflow）、生产案例较少。\n   - 适合：团队从开发到生产需要统一 Pipeline 抽象的中型团队。\n\n选型建议：\n- 数据处理为主的 Pipeline → Airflow\n- K8s 基础设施完善、需要端到端 ML 平台 → Kubeflow\n- 需要类型安全和缓存 → Flyte\n- 快速起步、灵活的 Backend 切换 → ZenML\n- 最小方案 → 直接 Python 脚本 + cron + shell（团队 < 5 人时）',
  ["ML Pipeline 编排的价值在于自动化和可复现——人工跑实验是不可复现的头号原因", "选择工具时考虑团队已有的基础设施（K8s → Kubeflow/Flyte，已有 Airflow → 不换）"],
  ["MLOps", "Pipeline", "Airflow", "Kubeflow", "工作流"])

# ==================== Security & Compliance ====================

q("ai_infra", "medium", "short_answer",
  'AI 基础设施安全：模型访问控制与数据隔离',
  'AI 基础设施特有的安全风险有哪些？模型访问控制（Model Access Control）、推理数据隔离、训练数据防泄漏的最佳实践是什么？',
  'AI 基础设施在传统安全基础上增加了模型安全和数据安全的新维度：\n\n1. 模型访问控制（Model Access Control）\n   风险：模型权重被窃取（开源模型专有微调版）、模型通过 API 被逆向（Model Extraction Attack——通过 API 查询反推模型结构或训练数据）。\n   措施：\n   - 模型存储加密：S3/GCS Bucket 服务侧加密（SSE-KMS）+ 访问策略限制到特定的 Service Account。\n   - 模型加载认证：推理服务启动时从 Registry 拉取模型需要 Token 认证（如 HuggingFace Token 或 Vault 签发的凭证）。\n   - API 鉴权：推理 API 需要 API Key / JWT 认证。区分不同的 API Key 权限级别（免费用户只能访问量化版本，付费用户访问全精度版）。\n   - Rate Limiting：限制同 IP/API Key 每小时的 Token 消耗量（防数据抽取攻击——攻击者通过大量 API 调用还原模型行为）。\n\n2. 推理数据隔离\n   风险：多租户推理时，A 用户的 Prompt 可能通过缓存或显存泄露给 B 用户。\n   措施：\n   - 显存清理：每个推理请求完成后清理其 KV Cache 和中间数据（vLLM/SGLang 的每个请求独立的 Block Table）。\n   - 进程级隔离：不同租户的推理请求分配到不同 Worker 进程（不共享内存空间）。\n   - 缓存隔离：语义缓存和 Response Cache 在 Key 中包含 Tenant ID，确保缓存不跨租户泄露。\n   - Log 脱敏：记录 API 调用日志前自动脱敏 PII（Personal Identifiable Information）。\n\n3. 训练数据防泄漏\n   风险：训练数据通过模型参数泄露（Membership Inference——判断某个样本是否在训练集中），或者通过生成内容泄露（不记得意地生成训练数据中的敏感信息）。\n   措施：\n   - 数据脱敏——在训练前对敏感数据（身份证号、邮箱、电话）做脱敏处理（替换为占位符或合成数据）。\n   - Differential Privacy（差分隐私）——训练时对梯度加入精心校准的噪声，限制模型能记住的信息量。\n   - 数据访问审计——训练数据的访问日志记录和审计（谁在什么时候访问了什么数据）。\n   - 训练数据分类——敏感数据（PII）和非敏感数据分不同的存储桶管理，严格控制敏感数据的访问范围。\n\n4. 供应链安全\n   风险：使用公共 HuggingFace Hub 上的模型可能包含恶意代码（Pickle 反序列化攻击、权重后门）。\n   措施：\n   - 模型扫描——使用安全工具（如 Pickle Scanner、ModelScan）检查模型文件中的恶意代码。\n   - 模型审核——在生产使用前，对开源模型的权重做审核（对比原始 Hash、检查是否篡改）。\n   - 私有模型 Registry——使用 HuggingFace Private Hub、MLflow Model Registry 或 S3 管理自有模型。\n   - 镜像安全——推理镜像定期扫描（Trivy / Snyk / Docker Scout），锁定基础镜像版本（不用 latest tag）。\n\n5. 网络隔离\n   - 推理服务部署在私有子网（不暴露公网 IP），通过 API Gateway / Ingress 暴露。\n   - 训练集群在完全隔离的网络环境中（无公网访问），通过 Jumpbox/Bastion 管理。\n   - 数据存储桶的访问策略限制到特定的 VPC Endpoint。',
  ["多租户推理的数据隔离是 AI 基础设施的核心安全挑战——KV Cache 和 Log 都可能泄露用户数据", "模型提取攻击（通过 API 查询反推模型）的防御主要靠 Rate Limiting 和结果扰动"],
  ["安全", "模型保护", "数据隔离", "多租户", "合规"])

q("ai_infra", "easy", "short_answer",
  '模型监控与数据漂移检测',
  '部署到生产的 ML 模型需要监控哪些指标？数据漂移（Data Drift）、概念漂移（Concept Drift）、预测漂移（Prediction Drift）的区别是什么？如何利用监控系统自动检测和应对漂移？',
  'ML 模型上线后的监控可以分为三个层次：基础设施监控、模型性能监控、业务指标监控。\n\n1. 基础设施监控\n   - GPU 利用率（SmActive、Tensor Activity）、GPU 温度、显存使用量\n   - 推理延迟（P50/P95/P99 逐 Token 延迟和端到端延迟）\n   - 请求吞吐（RPS / TPS——每秒请求数、每秒 Token 数）\n   - 错误率（4xx、5xx、模型推理 Error Rate）\n   - Batch Size 分布（反映 Batching 效率）\n\n2. 模型性能监控\n   - 在线评估指标：难以直接计算 accuracy（线上无标签），常用的替代指标：\n     * 用户反馈（Thumbs Up/Down 率）\n     * 内容安全（Safety Classifier 检测有害输出）\n     * 重试/放弃率（用户是否重复提问或放弃对话）\n     * 隐式信号（停留时间、对话轮数、是否复制输出）\n   - 离线评估：周期性（Daily/Weekly）用 Golden Dataset 评估线上模型的质量变化。\n\n3. 数据漂移监控——三种漂移类型：\n   a) 数据漂移（Data Drift / Covariate Shift）——输入数据的分布发生变化\n      例子：训练数据中用户 Query 平均长度 50 字，线上变成 200 字（用户变得更详细了）。\n      检测方法：计算参考分布（训练数据）和当前分布（生产数据）之间的统计距离（PSI/Population Stability Index、KL Divergence、Jensen-Shannon Distance）。\n      阈值：PSI > 0.1 标记 Warning，PSI > 0.25 标记 Drift。\n\n   b) 概念漂移（Concept Drift）——输入和输出的映射关系发生变化\n      例子：电商推荐模型——用户行为模式因季节或促销变化（夏天推荐短袖→秋天推荐外套）。模型认为的特征-标签关系已过时。\n      检测方法：如果有线上标签（延迟反馈），监控 accuracy/precision 随时间变化。没有线上标签时，监控模型输出的分布变化（Prediction Drift）作为代理信号。\n\n   c) 预测漂移（Prediction Drift）——模型输出的分布变化\n      检测方法：监控模型输出概率的分布（分类模型的置信度分布、生成模型的输出长度/风格分布）。\n      注意：预测分布变化不一定代表有问题——可能是季节性规律。需要结合业务知识判断。\n\n4. 漂移检测工具对比：\n   - WhyLabs / Whylogs——开源的数据漂移监控库。Whylogs 实时计算数据 Profile（统计摘要），上传到 WhyLabs 做漂移检测和可视化。\n   - Evidently AI——开源的 ML 监控库。支持 Data Drift、Target Drift、Model Performance 监控。生成 HTML Report。\n   - NannyML——开源的 Post-deployment ML 监控库，专门处理"没有线上标签时的性能估计"问题。使用 Confidence-based Performance Estimation 在没有 Ground Truth 时估计模型质量。\n\n5. 应对策略\n   - 自动告警：Drift 超过阈值 → 通知 MLOps Team / 自动触发 Re-training Pipeline。\n   - 模型回滚：新版本模型发生异常时自动回滚到上一个稳定版本。\n   - Shadow 部署：新旧模型同时运行，比较输出分布差异（发现 Drift 时触发告警但不影响线上流量）。\n   - 定期重训：设置定时任务（如每周）用最新数据重新训练模型，而不是等到 Drift 发生再处理。',
  ["数据漂移（输入分布变） vs 概念漂移（映射关系变） vs 预测漂移（输出分布变）——应对策略不同", "线上模型没有 Ground Truth 时，用用户行为信号（重试率、反馈）代替 accuracy 评估"],
  ["监控", "漂移检测", "MLOps", "模型质量", "可靠性"])

# ==================== Advanced Serving ====================

q("ai_infra", "hard", "short_answer",
  'LLM Serving 中的部署策略：Canary / Shadow / Blue-Green',
  'LLM 推理服务的部署策略有哪些？Canary Release、Shadow Deployment、Blue-Green Deployment 各自的适用场景和优劣？LLM 特有的 A/B 测试和评估指标是什么？',
  'LLM 服务部署比传统服务更复杂——新模型版本不仅可能有功能性差异，还可能改变输出的质量、风格、安全性。需要渐进式部署策略来降低风险。\n\n1. Blue-Green Deployment（蓝绿部署）\n   原理：保持两个完全相同的环境（Blue=当前生产，Green=新版本）。Green 环境准备好后，负载均衡器瞬间切换流量从 Blue 到 Green。\n   LLM 特有考虑：\n   - 模型在 Green 环境预热完成后（加载权重 + 编译 CUDA Graph）再切换流量\n   - 切换前在 Green 环境运行一次 Golden Test（用固定 Prompt 检查输出质量）\n   - 切换后 Blue 环境保持运行一段时间（等待正在处理的请求完成——LLM 推理可能持续数十秒）\n   优点：瞬间切换、快速回滚（切回 Blue）。\n   缺点：资源翻倍（Blue + Green 同时运行），成本高。\n   适用：关键生产环境（需要快速回滚的场景）。\n\n2. Canary Release（金丝雀发布）\n   原理：新版本逐步承接流量（如 5% → 20% → 50% → 100%），在每个阶段监控指标。\n   LLM 特有考虑：\n   - 金丝雀流量分配：基于请求粒度（不是用户粒度）。同一用户在同一个试段可能同时命中新旧版本。可以使用 Consistency Hash 保证同一用户落在同一版本。\n   - 监控指标：新版本 vs 旧版本的 Token 消耗、输出长度、语义质量（LLM-as-Judge 实时评估）、用户反馈率、安全违规率。\n   - 自动回滚：任一指标显著恶化（如 Safety Score 下降 > 5%），自动将金丝雀流量切回 0%。\n   优点：风险可控——发现问题时影响面小；可在真实流量上验证新模型。\n   缺点：回滚比 Blue-Green 慢（需要逐步降低流量）。\n   适用：模型升级（LLaMA-3-70B → LLaMA-4-70B）、推理引擎升级（vLLM v0.5 → v0.6）。\n\n3. Shadow Deployment（影子部署）\n   原理：新版本接收线上流量的镜像（复制请求），但不返回给用户。比较新旧版本的输出差异（不曝光用户到新版本）。\n   LLM 特有实现：\n   - 流量复制：请求同时发送到 Production 模型和 Shadow 模型。用户只收到 Production 模型的响应。\n   - 异步比较：存储 Shadow 模型的输出，然后异步比较与 Production 模型的质量差异。\n   - 成本：影子部署需要双倍 GPU 资源（Production + Shadow）。\n   优点：零用户影响——用户不会受到新版本问题的影响；可以收集真实流量下的质量数据。\n   缺点：成本高（双倍推理资源）；延迟敏感场景的流量复制可能影响 Production 服务。\n   适用：高风险模型升级（需要充分验证）、Prompt 或 RAG Pipeline 的重大变更。\n\n4. LLM 特有的 A/B 测试指标\n   传统 A/B 关注点击率、转化率等，LLM A/B 还需要：\n   - 语义质量：LLM-as-Judge 对 500-1000 个测试样本打分（准确率、完整性、连贯性）。\n   - 延迟指标：TTFT（Time to First Token）、TPOT（Time per Output Token）、端到端延迟。\n   - 成本指标：每请求 Token 消耗、每请求成本。\n   - 安全指标：安全违规率、PII 泄露率、对抗性测试通过的比率。\n   - 用户反馈指标：用户评分（Upvote/Downvote）、对话放弃率、用户复访率（7 日留存）。\n\n部署策略选择建议：\n日常模型升级 → Canary（风险可控，资源占用适中）\n关键升级（核心模型变更）→ Shadow（充分验证后切 Canary）\n紧急修复 → Blue-Green（快速切换 + 快速回滚）\n新功能评估 → Canary + A/B 分析（按用户组分配流量，对比指标）',
  ["Canary = 逐步切流量（日常最优），Shadow = 零影响验证（高风险升级），Blue-Green = 瞬间切（紧急/关键）", "LLM A/B 需要语义质量评估（LLM-as-Judge）和成本监控，不仅仅是传统业务指标"],
  ["部署", "Canary", "Shadow", "A/B测试", "模型服务"])

q("ai_infra", "medium", "short_answer",
  '模型压缩技术：蒸馏、剪枝与量化对比',
  '模型压缩的三条主要路径——知识蒸馏（Knowledge Distillation）、剪枝（Pruning）、量化（Quantization）——各自原理是什么？如何组合使用？各自的最佳适用场景？',
  "模型压缩是减少模型大小和推理成本的核心手段，三条路径互不冲突、可以组合。\n\n1. 知识蒸馏（Knowledge Distillation）\n   原理：用一个大的 Teacher 模型的知识训练一个小的 Student 模型。训练时 Student 不仅学习 Ground Truth 标签，还学习 Teacher 的软标签（Soft Label，即概率分布）。蒸馏损失 = α × Hard Loss（Cross Entropy with GT）+ (1-α) × Soft Loss（KL Divergence with Teacher's Distribution）。Temperature scaling——软化 Teacher 的概率分布（T > 1），使概率分布更平滑（包含更多的暗知识/Dark Knowledge）。\n   优势：可以极大缩小模型（如 70B → 7B）且保持大部分能力；不改变推理框架（Student 模型可直接用标准推理引擎）。\n   局限：需要训练（计算成本高）；依赖于 Teacher 模型的可用性。\n   典型场景：从 GPT-4（Teacher）蒸馏到 LLaMA-7B（Student）的指令遵循能力（如 Alpaca、Vicuna 系列）。\n\n2. 剪枝（Pruning）\n   原理：删除模型中不重要的权重或结构。\n   a) 非结构化剪枝——将权重值接近 0 的单个参数设为 0（权重矩阵变成稀疏矩阵）。需要稀疏矩阵硬件支持（NVIDIA 的 2:4 结构化稀疏——A100/H100 的 Sparse Tensor Core）。压缩率 2x，精度损失小。\n   b) 结构化剪枝——删除整个注意力头（Head）、MLP 层或 Channel。Transformer 的冗余——研究发现删除 30-50% 的 Attention Head 对性能影响很小。需要微调恢复。\n   c) 一次性剪枝→再训练（Iterative Pruning + Retraining）——剪掉一部分→微调恢复→再剪下一部分。效果好但耗时长。\n   优势：直接减少模型参数量和计算量（不仅仅是存储大小）。\n   局限：结构化剪枝需要微调（额外训练成本）；非结构化剪枝需要硬件支持（否则不能加速）。\n   典型场景：SparseGPT——无需微调的剪枝方法，在 LLaMA 上压缩 50% 且 perplexity 损失 < 1%。\n\n3. 量化（Quantization）（已在 LLM 量化题目中详细介绍）\n   简要对比：精度降低模型权重/激活的数值精度。INT8 减少 50% 显存，INT4 减少 75%。\n   方法：PTQ（训练后量化，简单快速）vs QAT（量化感知训练，精度更好但需要训练）。\n\n4. 三种方法的组合策略：\n   方案 A：量化（最常用）——效果 vs 成本比最好。仅需要少量校准数据，不需要训练。\n   方案 B：蒸馏 + 量化——先用蒸馏压缩模型规模（70B → 13B），再对 13B 做 INT4 量化（显存降到 ~7GB）。\n   方案 C：剪枝 + 量化——先结构化剪枝移除冗余 Head/Layer，然后 INT8 量化。\n   方案 D：全流程——蒸馏（减小模型规模）→ 剪枝（移除内部冗余）→ 量化（降低精度）。压缩率可达 10-20x（如 70B → 7B INT4，精度损失 2-5%）。\n\n5. 选择建议：\n   - 最紧急需要降成本 → 量化（快速见效，改动最小）\n   - 需要大幅缩小模型 → 蒸馏（规模压缩）\n   - 需要极致压缩 → 蒸馏 + 剪枝 + 量化组合\n   - 资源有限（无训练能力）→ 量化（PTQ，不需要训练）+ 结构化剪枝（SparseGPT）\n   - 精度敏感场景 → 只用 INT8 量化或不做量化，用蒸馏压缩",
  ["量化 = 最快最廉价的压缩（不需要训练），蒸馏 = 最大幅度的压缩（需要训练），剪枝 = 中间的平衡", "三种技术可以组合使用——典型流程：蒸馏压缩规模 → 剪枝去冗余 → 量化降精度"],
  ["模型压缩", "蒸馏", "剪枝", "量化", "优化"])

# ==================== Serving Infrastructure Operations ====================

q("ai_infra", "medium", "short_answer",
  '多模态推理基础设施',
  '多模态模型（视觉-语言、语音-文本）的推理基础设施和纯文本模型有什么不同？图像/音频的编码和推理 Pipeline 如何设计？多模态推理的瓶颈在哪里？',
  '多模态推理基础设施在纯文本 LLM 推理基础上增加了非文本数据的编码、处理和融合环节。\n\n1. 视觉-语言模型推理 Pipeline（如 GPT-4V、LLaVA、CLIP）\n   典型架构：Vision Encoder（如 ViT-L/14）→ Projection Layer → LLM Backbone\n   推理流程：\n   a) 图像编码——输入图像被 Resize/Patchify（如 336×336 → 576 patches of 14×14）。Vision Encoder（ViT）提取每个 Patch 的视觉特征（每个 Patch 变成 ~1024 维向量）。Prompt 中的图像被转换为固定数量的视觉 Token（如 576 个 Token/图像）。\n   b) 视觉 Token 融合——Projection Layer（通常是简单的线性层）将视觉特征映射到 LLM 的 Embedding 空间。视觉 Token 可以插入到文本 Token 序列的任意位置（或是前缀、或是穿插）。\n   c) 多模态推理——LLM 在视觉 Token + 文本 Token 的混合序列上进行自回归生成。\n\n   基础设施差异：\n   - 图像编码需要额外的 GPU 计算（ViT Forward Pass），约增加 10-30ms（取决于图像分辨率和编码器大小）。\n   - 图像 Token 数量大（576 Token/图像）——占用了 LLM 上下文窗口，增加了 KV Cache 大小。每张图相当于增加了 576 个输入 Token。\n   - 图像缓存：同一张图像在重复使用时（多轮对话中反复提及同一张图），ViT 编码结果可以缓存，避免重复编码。\n\n2. 音频模型推理（如 Whisper、SpeechT5、AudioLM）\n   Pipeline：Audio Frontend（特征提取）→ Encoder → Decoder（生成文本或音频）\n   a) 音频特征提取——原始音频波形（16kHz 采样率）→ Mel Spectrogram（80 维 Mel 滤波器组）→ 每帧 10ms，60 秒音频产生 6000 帧 → 6000 个音频 Token。\n   b) 推理特殊性——音频编码计算密集（FFT/Spectrogram 提取 + Encoder 计算）。需要实时能力（Streaming ASR 需要在说话的同时转录）。\n\n   基础设施差异：\n   - 音频编码需要 CPU/GPU 混合计算（FFT 最优在 CPU，Encdoer 在 GPU）。\n   - 音频编码后的 Token 序列可以很长（1 小时音频 ≈ 36000 Token）。\n   - 延迟敏感：实时语音交互需要 < 300ms 的端到端延迟。\n\n3. 多模态推理的瓶颈与优化：\n   a) 视觉 Token 数量爆炸——高分辨率图像（如 1344×1344）产生 ~4608 Token。优化：动态分辨率（根据图像内容自动选择分辨率）、视觉 Token 压缩（Perceiver Resampler 将 576 Token 压缩到 64 Token）。\n   b) 混合序列处理——视觉 Token 和文本 Token 混合的序列中，注意力计算的复杂度与总 Token 数呈平方关系。优化：Sparse Attention——图像 Token 之间不需要做 Attention（只关注文本 Token）。\n   c) 显存压力——多张大图的场景中，KV Cache 增长极快。优化：图像级别 KV Cache 的共享和复用（图像内容不变的轮次中复用上一步的视觉 KV Cache）。\n   d) 批处理——多模态推理中，不同图像的 Token 数量差异大（静图 576 Token，文本 50 Token → Batch Padding 效率低）。优化：动态 Batch 打包（把 Token 数相近的请求 batch 在一起）。\n\n4. 推理引擎支持现状：\n   - vLLM：支持 Vision-Language Model（LLaVA、Fuyu）的推理（实验性）。\n   - TGI（Text Generation Inference）：支持 Idefics、LLaVA 等多模态模型。\n   - TensorRT-LLM：支持 Vision 模型的 TensorRT 优化。\n   - Ollama：本地多模态模型运行的最友好选择（llava、bakllava、moondream）。',
  ["多模态推理比纯文本多了编码阶段（ViT/Audio Encoder），增加了延迟和 Token 数量", "视觉 Token 数量大是最核心的瓶颈——Token 压缩和 KV Cache 共享是主要优化方向"],
  ["多模态", "视觉", "推理", "GPU", "优化"])

# ==================== Benchmarking & Evaluation ====================

q("ai_infra", "hard", "short_answer",
  'AI 基础设施性能基准测试与容量规划',
  '如何对 AI 基础设施进行系统的性能基准测试？LLM 推理的吞吐、延迟、并发能力如何测量和建模？如何进行 GPU 容量规划以平衡成本和服务质量？',
  'AI 基础设施的基准测试和容量规划是基础设施工程的核心环节——没有数据支撑的容量决策是拍脑袋。\n\n1. 性能基准测试的维度\n   - 延迟（Latency）：\n     * TTFT（Time to First Token）：用户发出请求到收到第一个 Token 的时间。受模型大小、System Prompt 长度、Batch Size 影响。\n     * TPOT（Time Per Output Token/Speed）：每生成一个 Token 的平均时间。受内存带宽限制（Memory-Bound）。\n     * 端到端延迟 = TTFT + TPOT × Output Tokens。输出长文本（如 2000 Token）时 TPOT 主导。\n   - 吞吐（Throughput）：\n     * RPS（Requests Per Second）：每秒处理的请求数。受 Batch 策略和服务并发度影响。\n     * TPS（Tokens Per Second）：每秒生成的 Token 总数。TPS = Output Tokens × RPS。\n   - 并发（Concurrency）：\n     * Max Concurrent Requests：在不违反延迟 SLO 的前提下能同时处理的最大请求数。\n     * GPU Memory Utilization：显存是否成为瓶颈（通常是首因）。\n\n2. 负载测试方法论\n   Step 1: 定义 SLO——例如 P95 TTFT < 500ms，P95 TPOT < 30ms/token。\n   Step 2: 固定负载测试——恒定 RPS（如 10 req/s）持续 10 分钟，收集延迟分布。\n   Step 3: 阶梯负载测试——从 1 req/s 步进到 100 req/s，找到延迟 SLO 断裂点（Breakpoint）。\n   Step 4: 突发测试（Burst Test）——0 → 50 req/s 瞬间负载，观察系统恢复时间。\n   Step 5: 长时稳定性测试——持续 8-24 小时的目标负载，检查延迟漂移和 GPU Memory Leak。\n\n   工具：\n   - Locust（Python）——灵活的 HTTP 负载工具，支持自定义请求和指标收集。\n   - Hey / wrk——轻量级 HTTP 压测工具，适合快速压测。\n   - GenAI-Perf（NVIDIA 官方）——专门为 LLM 推理设计的负载测试工具（支持 vLLM、TGI、TRT-LLM）。\n\n3. 容量规划模型\n   - 公式法（粗略估算）：单 GPU 吞吐 = 输出速度（tokens/s/GPU）× 并发度。估算所需 GPU 数 = 预期峰值 RPS × 平均输出 Token 数 / 单 GPU TPS。\n   - 实际测试法（推荐）：在 1 GPU 上跑目标模型的负载测试 → 得到 1 GPU 的延迟-吞吐曲线 → 根据 SLO 找到 1 GPU 的 Max QPS → 目标 QPS / 1 GPU Max QPS = GPU 数量。\n   - 预留 Buffer：峰值比平均高 2-3x（典型互联网流量模式），Buffer = 计算值的 1.5x（安全系数）。\n\n4. 常见瓶颈和调优方向\n   | 瓶颈 | 症状 | 优化方向 |\n   |------|------|----------|\n   | GPU 显存 | OOM 或 Batch Size 受限 | 模型量化、Gradient Checkpointing、KV Cache 量化 |\n   | GPU 算力 | 高 SM Occupancy 但延迟大 | FlashAttention、TensorRT 编译优化、CUDA Graph |\n   | GPU 内存带宽 | TPOT 高于预期（Memory-Bound） | INT4 量化、KV Cache 量化、Speculative Decoding |\n   | CPU/网络 | TTFT 高但 TPOT 正常 | 优化 Tokenizer、优化网络延迟、使用 RDMA |\n   | Host 端瓶颈 | 预处理/后处理时间长 | Tokenizer 并行化、结果缓存 |\n\n5. 生产容量分配建议\n   - 推理和训练分集群部署（资源隔离，避免训练挤占推理资源）\n   - 推理服务设置 Queue（请求队列），当 Queue Depth > Threshold 时触发扩容（Scale-Up）\n   - 使用 Predictive Autoscaler（基于历史流量预测未来流量，提前扩容）\n   - 低峰期（夜间）缩减到最小副本数（Min Replicas = 1-2 用于保温）',
  ["容量规划的关键是实测（而不是估算）——在目标 GPU 上跑目标模型的负载测试", "延迟 SLO 决定最大吞吐——先定 SLO，再测能承受的最大 QPS，倒推 GPU 数量"],
  ["性能测试", "容量规划", "SLO", "GPU", "运维"])

# ==================== Write: Append to existing ai_infra.json ====================

output_path = "backend/seed_data/ai_infra.json"

# Read existing questions
with open(output_path, "r", encoding="utf-8") as f:
    existing = json.load(f)

# Append new questions (assigning new IDs is done by generate-data.js)
existing.extend(questions)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"Added {len(questions)} questions to {output_path}")
print(f"Total ai_infra questions: {len(existing)}")
