# -*- coding: utf-8 -*-
"""Generate additional design_network questions (append to existing JSON)."""
import json

questions = []

def q(cat, diff, typ, title, content, answer, hints, tags):
    questions.append({
        "category": cat, "difficulty": diff, "type": typ,
        "title": title, "content": content, "answer": answer,
        "hints": hints, "tags": tags
    })

# ==================== Routing & Transport ====================

q('design_network', 'hard', 'short_answer',
  'BGP 路由协议与 Anycast 实现原理',
  'BGP（Border Gateway Protocol）的核心工作原理是什么？Anycast 如何利用 BGP 实现流量调度？BGP 的路径选择算法（Path Selection）和路由策略（Routing Policy）如何影响网络拓扑设计？',
  "BGP 是互联网的核心路由协议，用于 AS（Autonomous System）之间的路由交换。\n\nBGP 基本原理：1）运行在 TCP 179 端口——可靠性由 TCP 保证，不需要 BGP 自身实现重传。2）Path Vector 协议——路由更新中携带完整的 AS Path（经过的 AS 列表），天然防止环路。3）EBGP（External BGP）——AS 之间的 BGP 对等体连接。IBGP（Internal BGP）——同一 AS 内的 BGP 对等体连接（IBGP 内要求全互联 Full Mesh 或 Route Reflector 解决扩展性问题）。\n\n路径选择算法（BGP Best Path Selection）：收到多条到同一目的地的路由时，BGP 按以下顺序选择（仅列出关键的）：1）Highest Weight（Cisco 私有，本地优先）。2）Highest Local Preference（控制 AS 出口流量选路）。3）Prefer locally originated routes。4）Shortest AS Path（最核心的选路标准）。5）Lowest MED（Multi-Exit Discriminator——控制 AS 入口流量选路）。6）Prefer EBGP over IBGP。7）Nearest IGP neighbor（到下一跳的 IGP 度量最小）。\n\nAnycast 与 BGP 的结合：Anycast 的核心思想——多个物理节点共享同一个 IP 地址。实现：这些节点的 BGP 路由器向互联网宣告同一条 IP 前缀。互联网上的路由器根据 BGP 路径选择算法（Shortest AS Path/最低 IGP Metric）自动将流量路由到最近的节点。DNS 根服务器（如 F Root 分布在全球数百个节点共享同一个 IP）和 CDN（Cloudflare、CloudFront）是 Anycast 的最大用户。\n\n路由策略实现：1）Route Map / Prefix List——控制路由的宣告和接受（如只向某个邻居宣告特定前缀）。2）AS Path Prepending——人为延长 AS Path 长度使某条路径不被优先选择（多宿主场景下实现流量冷/热备份）。3）Community——在路由上附加 Tag，下流 AS 根据 Community 执行预定义的策略。\n\nBGP 在云网络中的应用：云厂商（AWS、GCP）提供 Route Exchange（BGP Session 在 VGW/Virtual Router 和 On-Prem Router 之间建立），实现混合云网络互通。Dynamically routed VPN（动态路由 VPN）比 Static Route VPN 更灵活可靠。",
  ["BGP 的 AS Path 是最核心的选路标准——Shortest AS Path 优先", "Anycast = 多节点广播同 IP + BGP 选路决定流量去哪——CDN 和 DNS 的核心技术"],
  ['BGP', 'Anycast', '路由', 'CDN', '网络协议'])

q('design_network', 'medium', 'short_answer',
  'TLS/SSL 协议设计与优化',
  'TLS 握手协议（Handshake Protocol）的完整流程是什么？TLS 1.3 相比 1.2 的主要改进在哪里？HTTPS 的性能优化（TLS False Start、Session Resumption、OCSP Stapling）如何工作？',
  "TLS 是互联网安全传输的基石，经历了 SSLv2 → SSLv3 → TLS 1.0 → TLS 1.1 → TLS 1.2 → TLS 1.3 的演进。\n\nTLS 1.2 完整握手流程（7 次网络往返）：\n1. ClientHello——客户端发送支持的 TLS 版本、Cipher Suite 列表、随机数（Random）。\n2. ServerHello——服务端选择 TLS 版本、Cipher Suite、发送服务端随机数。\n3. Certificate——服务端发送证书链（Cert + Intermediate CA）。\n4. ServerKeyExchange（可选）——DH/ECDH 参数交换。\n5. ServerHelloDone。\n6. ClientKeyExchange——客户端发送 Premaster Secret（RSA 加密）或 DH 公钥。\n7. ChangeCipherSpec + Finished——握手结束。\n\nTLS 1.3 改进（2 次往返，1-RTT）：\n1. 精简握手——ClientHello 中直接包含 Key Share（基于之前支持的 Group 预生成密钥对）。ServerHello 直接包含服务器证书 + 完成验证。1-RTT 完成完整握手（vs TLS 1.2 的 2-RTT）。\n2. 移除不安全特性——删除 RSA Key Exchange（不具备前向安全性）、删除静态 DH、删除压缩、删除 Renegotiation。\n3. 0-RTT（Early Data）——之前通信过的客户端可以在 ClientHello 之后立即发送应用数据（需要 Server 已缓存 PSK Pre-Shared Key）。风险：容易遭受 Replay Attack（重放攻击）。\n4. 简化 Cipher Suite——只支持 AEAD Cipher（AES-GCM / ChaCha20-Poly1305）+ 强密钥交换（ECDHE/DHE）。\n\nHTTPS 性能优化技术：\n1. TLS False Start（TLS 1.2 优化）——客户端在发送 Finished 后立即发送应用数据（不等服务端的 Finished）。将 2-RTT 降到 1-RTT（在实际中）。\n2. Session Resumption（会话恢复）——Session ID（服务端缓存会话密钥）或 Session Ticket（服务端加密的 Ticket 发给客户端，客户端下次握手提交）。跳过证书验证和密钥协商，0-RTT 恢复（TLS 1.3 的 PSK）。\n3. OCSP Stapling——Online Certificate Status Protocol，客户端检查证书是否被吊销。传统方式是客户端直接请求 CA 的 OCSP Responder（额外延迟 + 隐私泄露）。OCSP Stapling——服务端定期从 CA 获取签名的 OCSP Response，在握手时直接附带（Certificate 消息中）。客户端不需要额外请求。\n4. 证书链优化——使用中间 CA 证书链不要过长（一般 2-3 级），减少 Certificate 消息大小。证书压缩技术。\n5. Connection Pooling——复用 TCP + TLS 连接（HTTP Keep-Alive / HTTP/2 Multiplexing）。减少重复握手次数。\n\n部署最佳实践：使用 TLS 1.3（优先）+ TLS 1.2（降级）。证书使用 ECDSA（更小更快）而不是 RSA。支持 HSTS（HTTP Strict Transport Security）头部防止降级攻击。",
  ['TLS 1.3 的核心改进是 1-RTT 握手（vs TLS 1.2 的 2-RTT）和 0-RTT 恢复', 'TLS False Start + Session Resumption + OCSP Stapling 是 HTTPS 性能优化的三板斧'],
  ['TLS', 'SSL', 'HTTPS', '安全', '性能优化'])

q('design_network', 'medium', 'short_answer',
  'Quic 协议详细设计',
  'QUIC（Quick UDP Internet Connections）传输协议的详细设计是什么？它如何结合 TCP 的可靠性和 UDP 的低延迟？Connection Migration 的机制和收益？',
  "QUIC 是 Google 设计、IETF 标准化的传输层协议（RFC 9000），基于 UDP，目标是替代 TCP + TLS + HTTP/2 的组合。\n\nQUIC 的核心设计：\n1. 传输层安全——QUIC 内置了 TLS 1.3（不是可选，是强制的）。握手 1-RTT（初次）或 0-RTT（恢复），将所有安全逻辑内置在传输层。\n2. 多路复用（彻底解决 HTTP/2 的队头阻塞）——TCP 的 H2 队头阻塞问题是根本性的：多个 HTTP 流共用一个 TCP 连接，一个 TCP 段丢失会阻塞后续所有 Stream（即使其他 Stream 数据已到达，TCP 的有序交付要求所有数据不按顺序）。QUIC 在单个连接内支持多个独立的 Stream——一个 Stream 上的数据丢失只影响该 Stream（其他 Stream 不受影响）。\n3. 加密和认证——QUIC 对传输头部也做了加密（TCP 头部是明文的），减少中间盒的干扰。只有连接 ID（后续用）是明文。\n\nConnection Migration（连接迁移）：\n原理：QUIC 使用 Connection ID 标识一个连接（不是 IP:Port 4 元组）。当客户端的网络变化（WiFi → 4G、NAT Re-binding、IP 地址变化）时，QUIC 使用相同的 Connection ID 在新地址上重建连接，不需要握手。\n流程：客户端从新 IP 发送一个包含原 Connection ID 的 QUIC Packet → 服务端通过 Connection ID 识别出已有连接 → 更新地址映射 → 继续传输。\n收益：移动网络切换（WiFi → Cellular）时 TCP 需要重新建立连接（新的 3 次握手 + TLS 握手），中断时间 500ms-2s。QUIC 的连接迁移实现无缝切换（中断时间 < 100ms）。对于移动 App（短视频、直播、实时通信）体验提升极大。\n\nQUIC 的流控和拥塞控制：\n1. 连接级流控（Connection-Level Flow Control）——限制整个连接上未读数据的字节数。\n2. Stream 级流控（Stream-Level Flow Control）——限制单个 Stream 上未读数据的字节数（与 H2 的流控不同——H2 只有 Connection 级流控）。\n3. 拥塞控制算法可插拔——QUIC 不绑定特定拥塞控制算法（TCP 绑定 Cubic/BBR），可以在用户空间选择/实现算法。常见：NewReno、Cubic、BBRv1/v2。\n\nQUIC 与 HTTP/3：HTTP/3 不是 QUIC 的上层——HTTP/3 = QUIC Transport + HTTP Layer（QPACK 替代 HPACK 做头部压缩）。IETF 将 QUIC 定义为传输层（类似 TCP），HTTP 语义在之上运行。\n\n部署现状：Google 产品（Chrome、YouTube、Search）使用 QUIC 多年（Google 内部版本 gQUIC）。IETF RFC 版本与 Google 版本不兼容。目前 ~40% 的 Web 流量使用 QUIC/HTTP/3。服务端支持（Nginx、Cloudflare、Caddy、LiteSpeed）已广泛可用。",
  ['QUIC 核心价值：多路复用无队头阻塞 + 连接迁移无缝切换 + 内置 TLS 1.3', 'HTTP/2 over TCP 的队头阻塞是设计瓶颈（TCP 有序交付导致），QUIC 的独立 Stream 从根本上解决'],
  ['QUIC', 'HTTP/3', '传输协议', 'UDP', '性能'])

q('design_network', 'medium', 'short_answer',
  'HTTP/2 多路复用的实现细节',
  'HTTP/2 多路复用的实现原理是什么？Stream、Frame、Message 的关系是什么？服务器推送（Server Push）和头部压缩（HPACK）如何工作？',
  "HTTP/2 的核心目标是通过多路复用（Multiplexing）消除 HTTP/1.1 的队头阻塞。\n\nHTTP/2 的 4 个核心概念：\n1. Stream（流）——一个双向的字节序列，对应一个 HTTP 请求-响应对。每个 Stream 有一个唯一的 Stream ID（客户端发起 ID 为奇数，服务端为偶数）。\n2. Frame（帧）——HTTP/2 的最小通信单元。类型：HEADERS、DATA、SETTINGS、PRIORITY、RST_STREAM、PUSH_PROMISE、GOAWAY。\n3. Message（消息）——一个完整的请求或响应，由多个 Frame 组成。\n4. Connection（连接）——一个 TCP 连接包含多个 Stream。\n\n多路复用：在同一个 TCP 连接上，多个 Stream 的 Frame 可以交错传输（Interleaving）。多个 HTTP 请求共享一个 TCP 连接，互相不阻塞。二进制分帧层（Binary Framing Layer）负责帧的封装和解析。\n\nHPACK 头部压缩：\n问题——HTTP 头部（Headers）冗余且大（Cookie、User-Agent、Authorization 等在每个请求中重复传输）。HTTP/1.1 中纯文本头部约 500-800 字节/请求。\nHPACK 压缩原理：\n1. 静态表（Static Table）——预定义了 61 个常用头部（如 :method: GET、:status: 200、content-type），用 1 字节索引表示。\n2. 动态表（Dynamic Table）——连接过程中动态添加新头部。客户端和服务端各自维护动态表，最大容量由 SETTINGS_HEADER_TABLE_SIZE 协商（默认 4096 字节）。\n3. Huffman 编码——对非静态表的头部值进行 Huffman 压缩（ASCII 常用字符压缩率 30-50%）。\n效果：头部从 500-800 字节压缩到 < 50 字节。\n\n服务器推送（Server Push）：\n原理——服务端在收到客户端请求后，预测客户端还会需要的资源（如 HTML 请求后 CSS/JS/图片），主动推送（不需要客户端先请求再响应）。\nPUSH_PROMISE Frame——服务端发送 PUSH_PROMISE 告知客户端即将推送的资源（包含资源 URL），客户端可以立即拒绝（RST_STREAM）如果已有缓存。\n效率：减少 RTT（客户端不需要先 GET HTML → 解析发现 CSS → 再 GET CSS）。\n\nHTTP/2 队头阻塞（仍然存在！）：虽然 HTTP/2 解决了应用层的队头阻塞（多个 HTTP 请求独立），但 TCP 层的队头阻塞仍然存在——TCP 段丢失会导致后续所有已到达的 TCP 段被阻塞在应用层读取之前。QUIC 在传输层解决这个问题。\n\nHTTP/2 的 Flow Control（流控）：基于 Stream 的 WINDOW_UPDATE 帧。每个 Stream 和整个 Connection 都有独立的流量控制窗口（Initial Window = 64KB）。防止慢速 Stream 被快速 Stream 挤出资源。\n\nHTTP/2 的 PRIORITY（优先级）：客户端可以设置 Stream 的优先级（依赖树 + 权重）。服务端根据优先级分配资源（bandwidth、CPU）。",
  ['HTTP/2 的 Stream + Frame 实现了请求级多路复用（解决 HTTP/1.1 的 HOL），但 TCP 层的 HOL 仍然存在', 'HPACK 的静态表 + 动态表 + Huffman 将头部从 800 字节压缩到 ~50 字节'],
  ['HTTP/2', '多路复用', 'HPACK', '性能', '协议'])

# ==================== Edge Computing & CDN ====================

q('design_network', 'medium', 'short_answer',
  '边缘计算架构与 CDN Edge Logic',
  '边缘计算（Edge Computing）的网络架构如何设计？CDN Edge Logic（边缘逻辑）的能力和限制是什么？边缘函数（Edge Function / Edge Workers）和 CDN 缓存的协同工作方式？',
  "边缘计算将计算能力从中心数据中心推到网络边缘（离用户更近的位置），降低延迟、减少中心负载。\n\n边缘计算的三层架构：\n1. 用户端（Device Layer）——手机、IoT 设备、浏览器。轻量处理（数据采集、简单过滤、缓存）。\n2. 边缘节点（Edge Layer）——CDN PoP 节点、5G MEC（Multi-access Edge Computing）节点。处理：请求路由、缓存服务、协议转换、实时推理（模型量化后部署在边缘 GPU）。延迟目标：< 10ms。\n3. 中心云（Central Cloud）——数据处理、模型训练、复杂业务逻辑、持久化存储。延迟目标：< 100ms。\n\nCDN Edge Logic 能力：\n现代 CDN（Cloudflare Workers、AWS CloudFront Functions/Lambda@Edge、Fastly Compute@Edge、Akamai EdgeWorkers）允许在 CDN 边缘节点执行自定义代码：\n1. 请求/响应修改——改写 URL、Header、Cookie、Redirect。不缓存可变内容，缓存静态内容。\n2. 权限校验——在边缘检查 JWT Token、API Key。只放行合法请求到源站（降低源站压力）。\n3. A/B 测试——按请求百分比/用户分组路由到不同源站地址。\n4. 个性化内容拼接——从多个后端聚合数据（Edge Side Includes / Edge Workers Fragment）。\n5. 响应变换——动态调整图片尺寸/格式（WebP → AVIF）、内容语言本地化、HTML 最小化。\n\nEdge Logic 的技术约束：\n- 计算资源限制：CPU 时间（通常 50μs-10ms/请求）、内存（通常 1-128MB）、代码大小。\n- 无状态设计：Edge Function 不应该依赖本地状态（全局分布式，不知道自己的物理位置）。\n- 冷启动：Edge Worker 可能被 Cold Start（冷启动延迟通常在 1-5ms，比 Serverless 好）。\n\nEdge 缓存策略：\n- TTL-based：静态资源（图片/CSS/JS）缓存 24-365 天。HTML 缓存 1-60 分钟。API 响应缓存 10-60 秒。\n- Stale-While-Revalidate：缓存过期后仍然返回陈旧内容（Stale），同时在后台异步更新（Revalidate）。用户无等待体验。\n- Cache Key 定制：CDN 缓存 Key 除了 URL 还可以包含（Device Type、Language、Cookie）。细粒度分片缓存。\n- Cache Reserve：CDN Edge 未命中时从 Cache Reserve 层（接近源站的近线缓存）取，而不是直接打到源站。\n\n网络架构注意：\n- Anycast 路由使 Edge 请求到达最近的 PoP。\n- Dynamic Backend Selection——Edge 节点根据用户地理位置/源站健康状态选择最优后端（回源负载均衡）。\n- Private Network Backbone——CDN 节点之间通过专线/私有骨干网通信（不经过公共互联网），保证回源质量。",
  ['边缘计算 = 在离用户最近的地方处理请求（< 10ms 延迟目标），不是所有请求都要回源站', 'Edge Function（Cloudflare Workers/Lambda@Edge）在 CDN 边缘执行轻量逻辑，减少源站压力'],
  ['边缘计算', 'CDN', 'Edge Function', '缓存', '架构'])

q('design_network', 'medium', 'short_answer',
  'WAF 与 Bot Management 网络架构',
  'Web 应用防火墙（WAF）的检测原理和部署架构是什么？Bot Management（机器人管理）如何通过流量分析区分人机和 API 客户端？Safe Browsing / DDoS Protection 如何与 WAF 协同？',
  "WAF（Web Application Firewall）是保护 Web 应用免受应用层攻击的核心安全组件。\n\nWAF 检测原理：\n1. 签名匹配（Signature-based）——维护已知攻击模式的签名库（SQL Injection、XSS、CSRF、RCE、Path Traversal）。OWASP ModSecurity Core Rule Set（CRS）是开源标准。局限：只能检测已知模式，需要定期更新规则。\n2. 异常检测（Anomaly-based）——建立请求正常行为的基线（请求速率、参数长度、内容类型分布）。偏离基线的请求标记为可疑。可检测 0-day 攻击，但有误报。\n3. 协议合规——检查 HTTP 协议合规性（非法 HTTP 方法、畸形请求头、Content-Length 不匹配）。大部分自动化攻击工具发送的 HTTP 请求不完全合规。\n4. Rate Limiting（速率限制）——单 IP/User 的请求速率超过阈值时触发阻断（基于 Token Bucket 或 Sliding Window）。\n\n部署模式：\n1. Inline Mode（透明代理）——WAF 串在流量路径中，直接阻断攻击请求。增加 1-3ms 延迟。\n2. Reverse Proxy Mode——WAF 作为反向代理（用户 → WAF → 源站），最灵活的部署（支持 SSL Termination、缓存、请求改写）。Cloudflare WAF、AWS WAF 使用此模式。\n3. Out-of-Band（旁路检测）——WAF 接收流量镜像，异步分析（不阻断流量）。发现攻击后通知上层设备（防火墙/路由）添加阻断规则。对生产流量零影响。\n\nBot Management 设计：\n1. 请求指纹——检测请求的 HTTP 指纹（User-Agent、Accept-Language、TCP/IP Stack Fingerprinting，如 JA3/JA3S TLS Fingerprint）。自动化工具（Selenium、Puppeteer）和正常浏览器在 TLS 握手/HTTP 头上有细微差别。\n2. JavaScript Challenge——服务端返回 JS Challenge（计算哈希、渲染 Canvas），浏览器环境可以自动执行，非浏览器（Curl/Requests）不能。\n3. CAPTCHA——Recaptcha、Turnstile（Cloudflare 的隐私友好版 CAPTCHA）。对 UX 有影响，只在高怀疑阈值时触发。\n4. 机器学习分类——基于请求特征（IP 信誉、行为模式、点击间隔、鼠标轨迹）训练 ML 模型分类 Human/Bot。Google 的 reCAPTCHA v3 使用完全不打扰用户的 ML 评分。\n6. API Protection——API 请求的 Bot 防护（用 API Key / OAuth + 请求签名 + 行为分析）。区分合法 API Client 和窃取了 API Key 的 BOT。\n\nWAF + DDoS + Safe Browsing 协同：\nDDoS Protection 处理 L3/L4 攻击（SYN Flood、UDP Amplification），在网络入口层过滤。WAF 处理 L7 攻击（SQLi、XSS），在应用层过滤。Safe Browsing（Google Safe Browsing / Cloudflare Phishing Protection）检测恶意 URL/域名。协同策略：流量入口 → DDoS 防护（过滤 L3/L4 攻击） → WAF（过滤 L7 攻击） → Bot Management（过滤自动化流量） → 应用。",
  ['WAF 的三层检测：签名匹配（已知攻击）+ 异常检测（未知攻击）+ 协议合规（畸形请求）', 'Bot Management 使用 JS Challenge + CAPTCHA + ML 分类组合策略区分人机和自动化工具'],
  ['WAF', '安全', 'Bot', 'DDoS', '防护'])

# ==================== Container Networking ====================

q('design_network', 'medium', 'short_answer',
  '容器网络模型：CNI、Cilium 与 eBPF',
  'Kubernetes 容器网络模型（CNI）的核心要求是什么？Cilium 如何使用 eBPF 实现高性能容器网络？Calico、Flannel、Cilium 的 CNI 方案对比和选型？',
  "Kubernetes 的网络模型（CNI——Container Network Interface）规定了每个 Pod 都拥有独立的 IP（Pod IP），Pod 之间可以直接通信（不需要 NAT），不通 Node 上的 Pod 也要能直接通信。\n\nCNI 的核心要求（K8s 网络模型）：\n1. Pod 在集群内拥有唯一的 IP 地址。\n2. 所有 Pod 可以直接与所有其他 Pod 通信（跨 Node 不需要 NAT）。\n3. 所有 Node 可以直接与所有 Pod 通信。\n4. Pod 看到的自己的 IP 就是其他 Pod 看到的它的 IP（无 NAT 转换）。\n\nCNI 实现方案对比：\n\n1. Flannel（最简单）\n   原理：Overlay Network（VXLAN 隧道）。在每个 Node 上分配一个子网（Subnet），Pod 经过 VXLAN 封装跨 Node 通信。\n   数据路径：Pod eth0 → veth Pair → cbr0 Bridge → flannel.1（VXLAN Tunnel） → Node eth0 → 目标 Node。\n   优点：部署简单（kubectl apply -f flannel.yml），资源开销低（不需要额外组件）。\n   缺点：VXLAN 封装有性能开销（约 10-15%），不支持 Network Policy（需要额外组件，如 Calico Policy-only 模式）。\n   适用：小集群、开发环境、对性能不敏感的集群。\n\n2. Calico（功能最全）\n   原理：纯三层路由（BGP）——每个 Node 作为 BGP Speaker，Pod IP 通过 BGP 路由通告到集群网络。不需要 Overlay 封装（性能好）。\n   特性：Network Policy（K8s NetworkPolicy + Calico GlobalNetworkPolicy）、BGP Peering（与物理网络设备交换路由）、IPIP 隧道（跨公有云的 Overlay 选项）。\n   优点：网络 Policy 功能最丰富（支持 L3-L4 策略）、BGP 路由性能好（无 Overlay 开销）。\n   缺点：配置较复杂（需要 BGP 知识）；大数据量路由表时 BGP 收敛慢。\n   适用：生产集群、需要丰富的网络安全策略的场景。\n\n3. Cilium（eBPF 方案）\n   原理：基于 eBPF（Extended Berkeley Packet Filter）在内核中动态注入网络处理程序。不依赖 iptables（性能比 Calico 更好）。\n   eBPF 的优势：直接在内核上下文中执行（不需要用户态-内核态切换）。XDP（eXpress Data Path）——网卡驱动层处理（比传统 TCP/IP 栈更快）。\n   Cilium 特性：1）Network Policy——L3-L7 策略（支持 HTTP/gRPC/Kafka 等协议的请求级过滤）。2）可观测性——Hubble 提供流量可视化（Service Map、流量策略验证、依赖分析）。3）Service Mesh——取代 Sidecar Proxy（通过 eBPF 实现透明流量拦截，不需要 Envoy 的 Sidecar 资源开销）。4）带宽管理——基于 eBPF 的带宽限制（Bandwidth Manager），比 CNI Bandwidth Plugin 更精确。\n   Cilium 的 Hubble 可以观察完整的集群网络流量图——对运维和故障排查非常有价值。\n   缺点：依赖 Linux 内核版本（4.19+，建议 5.10+）。eBPF 复杂度高（排查问题需要 eBPF 知识）。\n   适用：大规模生产集群、需要深度网络可观测性和高级网络策略的团队。\n\n选型建议：\n- 快速搭建、小集群 → Flannel（10 分钟搞定）\n- 生产集群、需要 Network Policy → Calico（功能稳定）\n- 需要高性能和深度可观测性 → Cilium（eBPF 方案，未来方向）\n- 云托管集群（EKS/GKE/AKS） → 使用云厂商自带的 CNI 插件（AWS VPC CNI、GKE Dataplane V2、Azure CNI），性能最好。",
  ['CNI 需要提供 Pod IP + 跨 Node Pod 通信（不 NAT）+ Network Policy（可选但推荐）', 'Cilium eBPF = 内核级网络处理（比 iptables 更快、更灵活），是容器网络的发展方向'],
  ['CNI', 'Cilium', 'eBPF', 'K8s', '容器网络'])

q('design_network', 'medium', 'short_answer',
  'Service Mesh 的流量管理与可观测性',
  'Service Mesh（服务网格）中流量管理（Traffic Management）和可观测性（Observability）的实现原理是什么？Istio 的 Sidecar Proxy（Envoy）如何处理流量？Data Plane vs Control Plane 的分工？',
  "Service Mesh 将微服务的通信逻辑从应用代码中抽离到基础设施层，以 Sidecar Proxy 的形式透明拦截和管理服务间流量。\n\nIstio 架构：Data Plane（数据面，Envoy Proxy）+ Control Plane（控制面，istiod）。\n\nData Plane（Envoy Proxy）：\n每个 Pod 中注入一个 Envoy Sidecar 容器。Envoy 拦截所有进出 Pod 的流量（通过 iptables 规则 redirect 流量到 Envoy 的监听端口）。\n\n流量拦截机制：\n1. Inbound 流量——请求到达 Pod eth0 → iptables REDIRECT → Envoy Inbound Listener（端口 15006）→ 处理策略→ 转发到应用容器端口。\n2. Outbound 流量——应用发出请求 → iptables REDIRECT → Envoy Outbound Listener（端口 15001）→ 查找目标 Service 的路由规则（VirtualService/DestinationRule）→ 选择目标实例 → 转发。\n\nEnvoy 的核心功能：\n1. 服务发现——Envoy 通过 Control Plane 获取集群中所有 Service 的端点列表（Endpoint Discovery Service/EDS）。\n2. 负载均衡——支持 Round Robin、Least Request、Ring Hash（一致性哈希）、Random。\n3. 健康检查——Envoy 主动探测端点健康状态（Active Health Check：HTTP/TCP/gRPC Health Check）。\n4. 熔断（Circuit Breaking）——当对端服务错误率过高时，Envoy 自动断开连接（停止发送请求），防止级联故障。\n5. 重试和超时——配置自动重试策略（Max Retries + Retry Timeout + Retry On：connect-failure/refused-stream/cancelled）和请求超时（Timeout）。\n6. 流量分割——基于权重（Weight-based）将流量按比例分配到不同版本（Canary Release：5% 流量到 v2，95% 到 v1）。\n7. 故障注入——注入延迟或错误来测试系统的容错性（Chaos Engineering）。\n\nControl Plane（istiod）：\n1. Pilot——服务发现和流量管理的控制逻辑。监控 K8s Service/Endpoint/ServiceEntry 变化 → 生成 Envoy 配置（Listener/Cluster/Route）→ 通过 xDS API 下发到所有 Envoy。\n2. Citadel——证书管理。自动为每个 Service Account 生成 SPIFFE 证书。实现 mTLS（自动加密服务间流量 + 身份认证）。\n3. Galley——配置验证和分发。\n\nxDS API（Envoy 的控制面 API）：\n- LDS（Listener Discovery Service）——监听器配置（监听哪个端口、处理什么协议）。\n- RDS（Route Discovery Service）——路由规则（什么请求去哪个 Cluster）。\n- CDS（Cluster Discovery Service）——后端服务集群定义（端点列表、负载均衡策略）。\n- EDS（Endpoint Discovery Service）——集群中具体的端点（Pod IP:Port）。\n- SDS（Secret Discovery Service）——TLS 证书。\n\n可观测性（Envoy 内置）：\n1. Metrics——Envoy 输出 Prometheus 格式的指标（请求总数、延迟直方图、错误率、活跃连接数）。通过 Grafana 可视化和告警。\n2. 分布式追踪——Envoy 自动生成 Trace Headers（x-request-id），配合 Jaeger/Zipkin 实现请求的全链路追踪。\n3. 访问日志——结构化日志（JSON 格式），包含源/目标 IP、延迟、响应码、协议等。\n\nService Mesh 的代价：每个请求增加 ~2-5ms 的 Sidecar 处理延迟。Envoy Sidecar 消耗额外的 CPU/Memory（约 50MB + 0.5 vCPU/Proxy）。",
  ['Envoy 通过 iptables 透明拦截所有流量，服务无感知', 'xDS API 是 Envoy 和控制面的通信协议——Pilot 将 K8s Service 变化实时同步到所有 Envoy'],
  ['Service Mesh', 'Istio', 'Envoy', '流量管理', '可观测性'])

# ==================== Network Automation & Observability ====================

q('design_network', 'easy', 'short_answer',
  '网络可观测性技术栈：NetFlow/sFlow/IPFIX 与 eBPF',
  '网络可观测性（Network Observability）的技术方案有哪些？NetFlow/sFlow/IPFIX 和 eBPF 技术的能力和局限是什么？如何在大型网络中采集和分析流量数据？',
  "网络可观测性是了解网络中流量的来源、去向、协议、延迟和异常的基石。\n\n主流网络流量采集技术：\n\n1. NetFlow（Cisco）/ IPFIX（IETF 标准化的 NetFlow v10）\n   原理：网络设备（路由器/交换机）采样流经的数据包，聚合为流记录（Flow Record）。每条流记录包含：源/目标 IP、源/目标端口、协议、包数、字节数、时间戳、ToS、AS 号等。\n   采样方式：NetFlow v5 全量采样（影响性能）；NetFlow v9/IPFIX 支持自定义模板（灵活选择字段）+ 可选采样（如 1:1000 采样率）。\n   局限：只能看到网络层和传输层信息（IP/Port），不能看到应用层内容（HTTP 路径、SQL 语句）；依赖网络设备支持。\n   工具：ELK（Elasticsearch + Logstash + Kibana）存储和展示 IPFIX 流数据；pmacct、ntopng 做流数据收集和聚合。\n\n2. sFlow（采样流）\n   原理：随机采样（如 1:4096 数据包采样）+ 定时计数器（接口的字节计数、CPU 负载）。采到的数据包直接封装为 sFlow 数据报发送到 Collector。\n   与 NetFlow 区别：sFlow 是采样 + 计数器（适合 10Gbps+ 高速网络），NetFlow 是流聚合（适合获取完整流信息）。sFlow Collector 端处理压力小。\n   适用：高速骨干网络（10Gbps/40Gbps/100Gbps 链路），全量流聚合太贵。\n\n3. eBPF（Extended Berkeley Packet Filter）\n   原理：在内核中注入程序，从网卡驱动层（XDP）或内核协议栈层捕获网络事件。零拷贝（不需要将数据包复制到用户态）。\n   可观测能力：L2-L7（MAC 地址 → HTTP Header/Message Body）。可以捕获 TCP 连接生命周期事件、HTTP 请求/响应、DNS 查询、TLS 握手等。\n   代表产品：\n   - Cilium Hubble——K8s 网络流量可视化（Service Map、L7 流量、连接跟踪）。\n   - Pixie——K8s 应用可观测性（自动捕获 HTTP/gRPC/HTTP2 请求、SQL 查询）。\n   - Falco——安全监控（检测异常 Syscall、容器逃逸行为）。\n   - Katran——高性能 L4 负载均衡器。\n   缺点：需要新内核（5.4+ 推荐）、eBPF 编程能力在问题排查时可能需要。\n\n网络数据采集的架构设计：\n1. 采集层——网络设备（NetFlow/sFlow）或 Host Agent（eBPF 程序）采集原始数据。\n2. 聚合层——流数据 Collector（pmacct、Logstash、Kafka）接收和缓冲数据。\n3. 存储层——时序数据库（ClickHouse、Elasticsearch）存储聚合后的指标。\n4. 分析层——Grafana、Kibana 做可视化。自定义告警规则（如：特定 AS 的流量突增 5 倍 → 告警）。\n\n实战建议：\n- 数据中心内部网络 → eBPF（Pixie/Hubble）——最佳的应用层可见性，适合微服务排障\n- 广域网/骨干网 → sFlow（高带宽场景下更轻量）\n- 企业网络/混合云 → IPFIX（网络设备原生支持，不需要额外 Agent）\n- 综合方案 = eBPF 做应用层可观测 + sFlow 做骨干网络可见 + IPFIX 做网络设备可见",
  ['NetFlow/IPFIX = 流聚合（网络设备级），sFlow = 随机采样（适合高速链路），eBPF = 内核级全量捕获（应用层可见性最好）', '综合使用多种技术——eBPF 看微服务通信，sFlow 看骨干流量，IPFIX 看网络设备状态'],
  ['网络可观测性', 'eBPF', 'NetFlow', 'sFlow', '监控'])

q('design_network', 'medium', 'short_answer',
  '网络自动化与基础设施即代码（IaC）',
  '网络自动化（Network Automation）如何落地？传统网络（手动 SSH 配置）如何迁移到 Infrastructure as Code？NetOps/GitOps 在网络管理中的最佳实践？',
  "网络自动化是将网络设备的配置管理从手动 SSH 命令转变为代码化、可版本管理、可自动化的流程。\n\n网络自动化的层次（从低到高）：\n\n1. 配置管理工具——Ansible、SaltStack、Puppet\n   方式：Ansible Playbook 定义网络配置变更（如修改 OSPF 配置、添加 VLAN、更新 ACL）。SSH 连接网络设备执行命令。\n   优势：兼容老旧设备（SSH 即可），学习成本低。\n   工具：Ansible + ios_config/vyos_config/junos_config 模块。NAPALM（Network Automation and Programmability Abstraction Layer with Multivendor support）——统一的多厂商 API。\n\n2. 声明式配置（Intent-based Networking）——NetBox + Batfish\n   方式：NetBox 作为 Source of Truth（IP 地址管理、设备清单、机架布局、连接关系）。Batfish 验证配置——将配置文件的意图与实际配置对比（解析配置 → 建立网络模型 → 验证可达性/安全策略）。\n   实践：变更流程——NetBox 修改 IP/Config → Batfish 验证 → Ansible 推送到设备。\n\n3. GitOps 网络管理（最先进的模式）\n   流程：Git Repository 存储网络配置 → 修改配置后提交 PR → CI 自动化验证（Batfish + Lint）→ 人工审核 → Merge → CD 自动推送到设备。\n   工具：\n   - Terraform Provider（网络设备 Terraform Provider，如 Juniper/Junos、F5 BIG-IP、Cisco Catalyst Center、Palo Alto Networks）。\n   - SaltStack + GitFS——Git 驱动的配置同步。\n   - Arista CloudVision / Cisco NSO——厂商的自动化平台。\n\n4. 网络策略即代码（Network Policy as Code）\n   工具：\n   - Terraform（AWS Security Groups、Azure NSG、GCP Firewall Rules 的声明式管理）。\n   - CiliumNetworkPolicy（K8s 网络策略的 Kubernetes CRD 方式管理）。\n   - OPA/Rego（Open Policy Agent）——通用策略引擎，可以编写网络访问控制规则。\n\n实践难点和解决方案：\n\n- 多厂商兼容性：YANG 模型（RFC 6020）+ NETCONF/RESTCONF 协议（标准化网络设备 API）。OpenConfig——Google 推动的标准化 YANG 模型（统一不同厂商的设备配置模型）。\n- 变更风险：模拟和验证先行——使用 Container Lab（Containerlab / CML / EVE-NG）在容器中运行网络设备的模拟版本，先在模拟环境验证变更。\n- 变更审计：所有网络配置变更通过 Git（有历史、有审核、有回滚）。traceroute/路径验证——在变更前后运行端到端连通性测试。\n- 配置一致性：Golden Configuration——定义标准配置模板（Base Config + 设备特定的变量）。每次配置漂移时自动修复。\n\n落地路线图：\n1. 第一步——Ansible 自动化重复操作（备份配置、批量修改密码、批量升级固件）。\n2. 第二步——NetBox 建立 Source of Truth（IPAM + DCIM）。\n3. 第三步——Terraform 管理公有云网络资源（VPC、Subnet、Security Group）。\n4. 第四步——GitOps 管理网络配置（全量网络设施代码化）。\n5. 第五步——Intent-based Networking（网络意图 → 自动推理 → 配置生成 → 验证）。",
  ['网络自动化的核心是 Source of Truth（NetBox） + 自动化执行（Ansible） + 验证（Batfish）', 'GitOps 网络管理（Terraform/PR/Batfish/CD）是最终形态——所有变更可审核、可回滚、可重复'],
  ['网络自动化', 'IaC', 'Ansible', 'GitOps', 'NetOps'])

q('design_network', 'medium', 'short_answer',
  'DPDK 与 XDP：高性能包处理技术',
  'DPDK（Data Plane Development Kit）和 XDP（eXpress Data Path）如何实现高速网络包处理？它们和传统内核网络栈的架构差异是什么？在什么场景下需要使用 DPDK/XDP？',
  "传统内核网络栈的瓶颈：数据包从网卡到应用经过多次拷贝和上下文切换（NIC → DMA Ring Buffer → 内核协议栈 → Socket Buffer → 应用 Buffer，每次需要中断通知 + Memcpy）。在 10Gbps/40Gbps 网络上，内核中断和内存拷贝开销极大。\n\nDPDK 方案：\n1. 原理——应用绕过内核协议栈，直接操作网卡硬件。使用 UIO（Userspace I/O）或 VFIO 将网卡控制寄存器映射到用户态。\n2. 关键组件：\n   - UIO/VFIO（用户态网卡驱动，不经过内核网络栈）\n   - Hugepages（2MB/1GB 大页内存，减少 TLB Miss）\n   - Poll Mode Driver（PMD，轮询驱动代替中断，减少上下文切换）\n   - Mempool（预分配的内存池，避免动态分配开销）\n3. 数据路径：网卡 DMA 写入 Hugepage → Poll Mode Driver 轮询检测新数据 → DPDK API 直接处理 → 应用处理。\n4. 性能：在 Intel Xeon 上单核可达 40M pps（包/秒），而传统内核栈约 1-2M pps。\n5. 场景：5G UPF（User Plane Function）、NFV（Network Function Virtualization，如虚拟路由器 vRouter）、高频交易。\n6. 代价：独占一个或多个 CPU 核（100% 轮询），DPDK 应用需要特定编程模型（不能使用标准 Socket API）。\n\nXDP（eBPF 方案，内核生态）：\n1. 原理——在网卡驱动层（最靠近硬件的位置）挂载 eBPF 程序。数据包到达网卡、被 DMA 到内存后立即被 eBPF 程序处理（再交给内核网络栈）。\n2. 数据路径：NIC → DMA → XDP eBPF（在内核中，数据包未进入协议栈）→ 动作：DROP/PASS/TX/REDIRECT。\n   - XDP_DROP：直接丢弃（高性能 DDoS 防护）。\n   - XDP_TX：从收到的网卡直接转发出去（实现简单路由器/负载均衡器）。\n   - XDP_REDIRECT：重定向到其他网卡或 AF_XDP Socket。\n   - XDP_PASS：交给内核网络栈继续处理（标准的 TCP/IP 处理）。\n3. 性能：在 10Gbps 网卡上单核可达 20-26M pps（比 DPDK 低一些，但远高于传统内核栈）。\n4. 优势：不需要独占 CPU 核（事件驱动，没有数据时不轮询）。使用标准内核接口（eBPF 程序加载即可）。可以和传统网络栈共存——XDP_PASS 让流量回到内核栈。\n5. 场景：DDoS 防护（Cloudflare 使用 XDP 在边缘节点过滤攻击流量）、L4 负载均衡器（Cilium/Katran 使用 XDP 做高效转发）、K8s Service Load Balancing（Cilium 使用 XDP）。\n\nDPDK vs XDP 对比：\n- 性能：DPDK 领先（40M vs 26M pps），但差距在縮小。\n- 易用性：XDP 更好（内核标准，无需修改应用，不需要特定编程模型）。\n- 灵活性：DPDK 完全控制数据路径（可以做任意处理），XDP 受 eBPF 的限制（不能死循环、不能调用任意内核函数、指令数有限制）。\n- 部署：XDP 需要内核 4.8+（推荐 5.4+），DPDK 需要 UIO/VFIO 驱动支持。\n- 未来趋势：XDP 是发展方向（Cloudflare、Cilium/Katran 使用 XDP），DPDK 在高性能 NFV/5G 场景仍然重要。\n\n选型建议：\n- DDoS 防护（需要快速丢包）→ XDP（DROP 动作极快，不占用 CPU 做轮询）\n- 4/7 层负载均衡 → XDP（Cilium/Katran 方案，集成在 K8s 生态）\n- 5G/NFV 虚拟化网络功能 → DPDK（运营商标准方案，性能最高）\n- 高频交易 → DPDK（极致延迟优化，纳秒级处理）",
  ['DPDK = 用户态轮询 + 绕过内核（最高性能，40M pps），XDP = 内核 eBPF 驱动层处理（更易用，26M pps）', 'XDP 是 DDoS 防护的最佳选择（DROP 动作极快，不浪费 CPU），DPDK 在高性能 NFV/5G 场景重要'],
  ['DPDK', 'XDP', 'eBPF', '高性能网络', '包处理'])

q('design_network', 'hard', 'short_answer',
  '全球流量调度：GTM / Traffic Steering / 多活路由',
  '全球流量管理（Global Traffic Management, GTM）如何设计？基于 DNS 的流量调度和基于 Anycast 的流量调度各自的优劣？多活架构中的流量入站（Ingress）和出站（Egress）路由策略如何设计？',
  "全球流量管理解决的核心问题：将不同地理位置的用户流量导向最优的数据中心（最低延迟、最高可用性）。\n\n两种核心调度技术：\n\n1. DNS-based Traffic Steering（基于 DNS 的流量调度）\n   原理：权威 DNS 服务器根据用户的地理位置/网络延迟/CDN 健康状态返回不同的 IP（A/AAAA 记录或 CNAME）。\n   实现方式：\n   - GeoDNS——根据用户的 EDNS Client Subnet（ECS，网络运营商提供的用户地理位置信息）返回最近的 IP。\n   - Latency-based Routing（AWS Route 53）——持续探测各 Region 的延迟，将用户路由到延迟最低的端点。\n   - Weighted Round Robin——按权重分配流量到不同的端点（Canary Release、蓝绿部署）。\n   优点：简单、成熟（全球权威 DNS 基础设施）。\n   缺点：DNS 缓存（TTL 最长可到 86400 秒，变更生效慢）；DNS 无法感知端点的实时健康状态（DNS 解析和请求到达之间有间隔）；基于 DNS 的调度无法做到请求级的负载均衡。\n   适用：全局层面的流量调度（Region 间的分配）。\n\n2. Anycast-based Traffic Steering（基于 Anycast 的流量调度）\n   原理：多个数据中心宣告相同的 IP 前缀（BGP Anycast），互联网的 BGP 路由自动将用户流量导向最近的数据中心。\n   实现：每个数据中心的边缘路由器和互联网骨干路由器建立 EBGP Session，宣告相同的前缀。BGP AS Path / MED / Community 控制流量分布。\n   优点：实时生效（BGP 路由变化立即影响流量流向）；请求级自动故障切换（一个数据中心故障时，BGP Withdraw 该前缀，流量自动切到其他数据中心）。\n   缺点：BGP 路由不稳定可能导致全球路由表抖动（Flapping）；BGP 无法做到精确的流量比例分配；Anycast IP 的 TCP 连接在故障切换时会断开（需要应用层重试）。\n   适用：CDN（Cloudflare、Fastly）、DNS 根服务器、UDP 类服务（QUIC、VoIP），以及无状态协议的入口。\n\n多活架构的流量策略：\n\n入站（Ingress）流量：\n1. Active-Passive（主备）——DNS 只返回主数据中心 IP。主中心故障时手动或自动切换 DNS 记录到备用中心。简单但资源利用率低。\n2. Active-Active（多活）——所有数据中心同时接收流量。DNS GTM 将用户分流到最近/延迟最低的数据中心。需要跨 Region 数据同步（最终一致性或分布式事务）。\n3. Proximity + Load-based（就近 + 容量感知）——DNS GTM + 端点健康检查 + 容量感知（AWS Route 53 的 Multi-value Answer/Route 53 Traffic Flow）。流量优先到最近的数据中心，但该中心容量接近时，部分流量被路由到次优数据中心。\n\n出站（Egress）流量：\n1. Local Breakout（本地出口）——每个数据中心直接连接本地 ISP 出站（不绕回总部）。延迟最低。\n2. Backbone Routing（骨干回传）——所有出站流量通过企业骨干网集中到一个出口点。策略控制方便（集中式安全检查和审计），但延迟增加。\n3. 混合策略——出站目的地址是 CDN/公有云走 Local Breakout（低延迟），出站到业务伙伴/合规监管地区走 Backbone（安全控制）。\n\n多活的关键挑战：\n1. 数据一致性问题——用户在 Region A 写入数据 → 被 DNS 调度到 Region B 读取 → 数据未同步到 B → 读到旧数据或报错。\n2. 故障切换粒度——Region 级切换太粗（一个 Region 的一部分服务故障会导致整个 Region 被切换），Service 级切换太复杂。\n3. 流量比例控制——修改 BGP 策略或 DNS TTL 来调整跨 Region 流量比例，生效时间不可控。\n\n推荐工具：\n- AWS Route 53（DNS GTM）、Azure Traffic Manager（DNS GTM）\n- Google Cloud Global Load Balancer（Anycast-based，单一 Anycast IP 自动最优路由）\n- NS1（高级 DNS GTM，支持 Filter Chain——灵活的流量调度规则链）\n- Edge DNS + GSLB（F5/A10/Citrix 的全局服务器负载均衡器，健康检查 + DNS 联动）",
  ['DNS GTM = 全局流量分配（Region 级，有缓存延迟），Anycast = 实时流量调度（PoP 级，即时切换）', '多活架构的核心挑战不是网络——是数据一致性（跨 Region 数据同步决定了你能做到什么级别的多活）'],
  ['GTM', 'Anycast', 'DNS', '多活', '流量调度'])

q('design_network', 'medium', 'short_answer',
  '网络延迟优化：TCP 和 HTTP 的端到端性能优化',
  '从用户请求到服务端响应的端到端链路中，各阶段的延迟构成是什么？如何系统性地优化网络延迟？TCP 参数调优、HTTP 协议优化、传输优化的最佳实践？',
  "端到端的网络延迟构成可以用公式表示：延迟 = DNS 解析 + TCP 握手 + TLS 握手 + 请求传输 + 服务器处理 + 响应传输。按 50ms RTT（跨洲典型值）计算各环节的分解。\n\n1. DNS 解析优化\n   延迟构成：递归 DNS 查询（通常 10-50ms，取决于 DoH/DoT 还是传统 DNS）。\n   优化：\n   - DNS 预取（<link rel='dns-prefetch'>）——在 HTML 中预先解析第三方域名。\n   - DNS Caching——确保 DNS TTL 设置合理（稳定的 IP 用 300-600 秒，避免太长导致迁移慢）。\n   - HTTPDNS（用户端直接 HTTP 请求 DNS 服务，避免 Local DNS 污染和递归延迟）。\n\n2. TCP 连接优化\n   延迟构成：3 次握手（1.5 RTT，约 75ms）。\n   优化：\n   - TCP Fast Open（TFO）——在 TCP 握手的 SYN 包中就携带数据（节省 1 RTT）。服务端和客户端都需要支持。\n   - 连接池——复用 HTTP Keep-Alive / HTTP/2 Multiplexing / gRPC Long-lived Connection。避免重复握手。\n   - TCP 参数调优：\n     * 初始窗口（initcwnd）——建议至少 10 个段（RFC 6928），快速开始数据传输。\n     * 拥塞控制算法——数据中心内用 BBR（对丢包不敏感，充分利用带宽）或 Cubic（互联网通用），数据中心间高带宽链路用 BBR。\n     * 缓冲区大小（tcp_rmem/tcp_wmem）——自动调整（auto-tuning）通常已开启，但可以调大 max 值（如 net.core.rmem_max = 16777216）。\n     * Nagle 算法——实时交互场景禁用 TCP_NODELAY（减少低延迟场景的 Nagle 延迟）。\n\n3. TLS 优化（已在前面的 TLS 题目中详细讨论）\n   关键要点：TLS 1.3（1-RTT）+ Session Resumption（0-RTT）+ OCSP Stapling。\n\n4. HTTP 层优化\n   延迟构成：请求传输时间数据量÷带宽。\n   优化：\n   - HTTP/2 Multiplexing（多路复用降低 TCP 连接数，减少慢启动开销）。\n   - HTTP/3（QUIC）——消除 TCP 的队头阻塞 + 0-RTT 握手。\n   - 资源压缩：Brotli（比 Gzip 压缩率 20%+）、图片 AVIF/WebP、字体子集化。\n   - Preconnect/Preload/Prefetch——浏览器的资源提示（Resource Hints）。\n   - 服务端推送（Server Push）——HTTP/2 Server Push（已逐渐不被推荐，实际效果差）。更推荐 103 Early Hints（HTTP 状态码预先推送关键资源链接）。\n\n5. CDN 加速（减少物理距离）\n   静态资源部署到 CDN（图片/CSS/JS）。CDN 边缘节点距离用户 < 10ms。动态请求加速——CDN 通过专线回源（比公网更快更可靠）。\n\n6. 协议传输效率优化\n   - 序列化——JSON → Protocol Buffers / FlatBuffers（减少传输大小 + 提高解析速度）。\n   - Streaming——大量数据的场景使用 Stream（gRPC Stream / Server-Sent Events）分批传输，不需要等到全部数据准备好再发送。\n   - 压缩——请求/响应中的大 payload 使用 Gzip/Brotli 压缩。\n\n系统性优化路线图：\n第一层（最快见效）：启用 CDN + HTTP/2 + Gzip/Brotli 压缩 + 连接池。\n第二层（中等投入）：迁移到 HTTP/3/QUIC + Brotli 级别调优 + 调整 TCP 参数。\n第三层（高投入）：全球多活 + Anycast + HTTPDNS + 自定义传输协议（QUIC + 0-RTT + 连接迁移）。",
  ['端到端延迟的每步优化：DNS 预取 → TCP/TLS 优化 → HTTP 协议升级 → CDN → 传输效率', '最快见效的三件事：启用 CDN + HTTP/2 + 连接池——不需要改代码就能获得 30-50% 延迟改善'],
  ['延迟优化', 'TCP', 'HTTP', 'CDN', '性能'])

# ==================== Write: Append ====================

output_path = 'backend/seed_data/design_network.json'

with open(output_path, 'r', encoding='utf-8') as f:
    existing = json.load(f)

existing.extend(questions)

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f'Added {len(questions)} questions to {output_path}')
print(f'Total design_network questions: {len(existing)}')
